// pos-client/src/pages/sales/Index.jsx
import { useState, useEffect, useRef } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useGetSalesQuery, useDeleteSaleMutation } from '../../features/sales/salesApi';
import { useSelector } from 'react-redux';
import { selectRole } from '../../features/auth/authSlice';
import { useLocale } from '../../contexts/LocaleContext';

export default function SalesIndex() {
  const role = useSelector(selectRole);
  const canDelete = role === 'admin';
  const navigate = useNavigate();

  // Barcode scanner: fast keystrokes → navigate to POS with barcode pre-loaded
  const barcodeRef  = useRef('');
  const barcodeTimer = useRef(null);
  const lastKey      = useRef(0);
  useEffect(() => {
    const onKey = e => {
      if (document.activeElement?.tagName === 'INPUT') return;
      if (e.key === 'Enter') {
        const bc = barcodeRef.current.trim();
        barcodeRef.current = '';
        clearTimeout(barcodeTimer.current);
        if (bc.length >= 3) navigate('/sales/create', { state: { barcode: bc } });
        return;
      }
      if (e.key.length !== 1) return;
      const now = Date.now();
      const gap = now - lastKey.current;
      lastKey.current = now;
      if (gap > 500) barcodeRef.current = '';
      barcodeRef.current += e.key;
      clearTimeout(barcodeTimer.current);
      barcodeTimer.current = setTimeout(() => { barcodeRef.current = ''; }, 500);
    };
    window.addEventListener('keydown', onKey);
    return () => { window.removeEventListener('keydown', onKey); clearTimeout(barcodeTimer.current); };
  }, [navigate]);
  const { t } = useLocale();

  const [search, setSearch] = useState('');
  const [date, setDate]     = useState('');
  const [page, setPage]     = useState(1);
  const [applied, setApplied] = useState({});

  const { data, isLoading } = useGetSalesQuery({ ...applied, page });
  const [deleteSale] = useDeleteSaleMutation();

  function handleSearch(e) {
    e.preventDefault();
    setApplied({ search, date });
    setPage(1);
  }

  async function handleDelete(id, inv) {
    if (!window.confirm(`Delete sale ${inv}?`)) return;
    await deleteSale(id);
  }

  const fmt = n => 'Rs. ' + Number(n || 0).toLocaleString('en-LK', { minimumFractionDigits: 2 });
  const fmtDate = s => new Date(s).toLocaleDateString('en-LK');
  const fmtTime = s => new Date(s).toLocaleTimeString('en-LK', { hour: '2-digit', minute: '2-digit' });

  const statusBadge = status => {
    const cls = { completed: 'bg-green-100 text-green-700', held: 'bg-yellow-100 text-yellow-700', returned: 'bg-red-100 text-red-700' };
    return <span className={`text-xs px-2 py-0.5 rounded-full font-semibold capitalize ${cls[status] || 'bg-slate-100 text-slate-600'}`}>{status}</span>;
  };

  const payMethod = payments => {
    if (!payments?.length) return '—';
    const methods = [...new Set(payments.map(p => p.method))].join(', ');
    return <span className="capitalize">{methods}</span>;
  };

  return (
    <div className="p-3 sm:p-6 space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-xl font-bold text-slate-800">{t('page.sales')}</h1>
        <Link to="/sales/create" className="px-4 py-2 bg-blue-600 text-white text-sm font-semibold rounded-lg hover:bg-blue-700 transition-colors">
          + {t('btn.new_sale')}
        </Link>
      </div>

      {/* Filters */}
      <form onSubmit={handleSearch} className="bg-white rounded-xl p-4 shadow-sm border border-slate-100 flex flex-wrap gap-3 items-end">
        <div className="flex-1 min-w-40">
          <label className="block text-xs font-semibold text-slate-600 mb-1">{t('th.invoice')}</label>
          <input value={search} onChange={e => setSearch(e.target.value)} placeholder="INV-0001"
            className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-blue-500" />
        </div>
        <div>
          <label className="block text-xs font-semibold text-slate-600 mb-1">{t('th.date')}</label>
          <input type="date" value={date} onChange={e => setDate(e.target.value)}
            className="rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-blue-500" />
        </div>
        <button type="submit" className="px-4 py-2 bg-slate-800 text-white text-sm font-semibold rounded-lg hover:bg-slate-700 transition-colors">
          {t('btn.search')}
        </button>
        {Object.values(applied).some(Boolean) && (
          <button type="button" onClick={() => { setApplied({}); setSearch(''); setDate(''); setPage(1); }}
            className="px-4 py-2 border border-slate-200 text-sm text-slate-600 rounded-lg hover:bg-slate-50 transition-colors">
            {t('btn.clear')}
          </button>
        )}
      </form>

      {/* Mobile cards */}
      <div className="md:hidden space-y-2">
        {isLoading && <div className="p-8 text-center text-slate-400 text-sm bg-white rounded-xl border border-slate-100">{t('lbl.loading')}</div>}
        {!isLoading && !(data?.data?.length) && (
          <div className="p-8 text-center text-slate-400 text-sm bg-white rounded-xl border border-slate-100">{t('lbl.no_results')}</div>
        )}
        {(data?.data || []).map(s => (
          <Link key={s.id} to={`/sales/${s.id}`}
            className="block bg-white rounded-xl border border-slate-100 shadow-sm p-4 hover:border-blue-200 hover:shadow-md transition-all active:scale-[0.99]">
            {/* Top row: invoice + status */}
            <div className="flex items-center justify-between mb-2">
              <span className="font-mono text-blue-600 font-bold text-sm">{s.invoice_no}</span>
              {statusBadge(s.status)}
            </div>
            {/* Middle: date + total */}
            <div className="flex items-center justify-between mb-2">
              <div>
                <p className="text-xs text-slate-500">{fmtDate(s.created_at)} · {fmtTime(s.created_at)}</p>
                <p className="text-xs text-slate-400 mt-0.5 capitalize">{payMethod(s.payments)}</p>
              </div>
              <span className="text-base font-extrabold text-slate-800">{fmt(s.total)}</span>
            </div>
            {/* Bottom: customer + cashier + delete */}
            <div className="flex items-center justify-between pt-2 border-t border-slate-50">
              <div className="flex gap-3 text-xs text-slate-500">
                <span>{s.customer?.name || '—'}</span>
                <span className="text-slate-300">|</span>
                <span>{s.user?.name || '—'}</span>
              </div>
              {canDelete && (
                <button
                  onClick={e => { e.preventDefault(); e.stopPropagation(); handleDelete(s.id, s.invoice_no); }}
                  className="text-xs text-red-400 hover:text-red-600 font-medium px-2 py-0.5 hover:bg-red-50 rounded transition-colors">
                  {t('btn.delete')}
                </button>
              )}
            </div>
          </Link>
        ))}
        {data && data.last_page > 1 && (
          <div className="flex items-center justify-between px-2 py-2 text-sm text-slate-500">
            <span>{data.total} {t('nav.sales')}</span>
            <div className="flex gap-2">
              <button disabled={page <= 1} onClick={() => setPage(p => p - 1)} className="px-3 py-1.5 rounded-lg border border-slate-200 disabled:opacity-40 hover:bg-slate-50">{'‹'}</button>
              <span className="px-2 py-1">{page} / {data.last_page}</span>
              <button disabled={page >= data.last_page} onClick={() => setPage(p => p + 1)} className="px-3 py-1.5 rounded-lg border border-slate-200 disabled:opacity-40 hover:bg-slate-50">{'›'}</button>
            </div>
          </div>
        )}
      </div>

      {/* Desktop table */}
      <div className="hidden md:block bg-white rounded-xl shadow-sm border border-slate-100 overflow-hidden">
        {isLoading ? <div className="p-8 text-center text-slate-400 text-sm">{t('lbl.loading')}</div> : (
          <div className="overflow-x-auto"><table className="w-full text-sm">
            <thead className="bg-slate-50 text-xs text-slate-500 uppercase tracking-wider">
              <tr>
                <th className="px-4 py-3 text-left font-semibold">{t('th.invoice')}</th>
                <th className="px-4 py-3 text-left font-semibold">{t('lbl.date_time')}</th>
                <th className="px-4 py-3 text-left font-semibold">{t('lbl.customer')}</th>
                <th className="px-4 py-3 text-left font-semibold">{t('lbl.cashier')}</th>
                <th className="px-4 py-3 text-right font-semibold">{t('th.total')}</th>
                <th className="px-4 py-3 text-center font-semibold">{t('th.method')}</th>
                <th className="px-4 py-3 text-center font-semibold">{t('th.status')}</th>
                <th className="px-4 py-3 text-right font-semibold">{t('th.actions')}</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50">
              {(data?.data || []).map(s => (
                <tr key={s.id} className="hover:bg-slate-50">
                  <td className="px-4 py-3 font-mono text-blue-600 font-semibold">{s.invoice_no}</td>
                  <td className="px-4 py-3 text-slate-500">
                    <p>{fmtDate(s.created_at)}</p>
                    <p className="text-xs text-slate-400">{fmtTime(s.created_at)}</p>
                  </td>
                  <td className="px-4 py-3 text-slate-600">{s.customer?.name || '—'}</td>
                  <td className="px-4 py-3 text-slate-600">{s.user?.name || '—'}</td>
                  <td className="px-4 py-3 text-right font-semibold text-slate-800">{fmt(s.total)}</td>
                  <td className="px-4 py-3 text-center text-slate-500">{payMethod(s.payments)}</td>
                  <td className="px-4 py-3 text-center">{statusBadge(s.status)}</td>
                  <td className="px-4 py-3 text-right whitespace-nowrap space-x-3">
                    <Link to={`/sales/${s.id}`} className="text-blue-600 hover:text-blue-800 font-medium">{t('btn.view')}</Link>
                    {canDelete && (
                      <button onClick={() => handleDelete(s.id, s.invoice_no)} className="text-red-500 hover:text-red-700 font-medium">{t('btn.delete')}</button>
                    )}
                  </td>
                </tr>
              ))}
              {!(data?.data?.length) && (
                <tr><td colSpan={8} className="px-4 py-8 text-center text-slate-400">{t('lbl.no_results')}</td></tr>
              )}
            </tbody>
          </table></div>
        )}
        {data && data.last_page > 1 && (
          <div className="flex items-center justify-between px-4 py-3 border-t border-slate-100 text-sm text-slate-500">
            <span>{data.total} {t('nav.sales')}</span>
            <div className="flex gap-2">
              <button disabled={page <= 1} onClick={() => setPage(p => p - 1)} className="px-3 py-1 rounded border border-slate-200 disabled:opacity-40 hover:bg-slate-50">{'‹'}</button>
              <span className="px-2 py-1">{page} / {data.last_page}</span>
              <button disabled={page >= data.last_page} onClick={() => setPage(p => p + 1)} className="px-3 py-1 rounded border border-slate-200 disabled:opacity-40 hover:bg-slate-50">{'›'}</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// resources/js/Pages/Sales/Index.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, router } from '@inertiajs/vue3';
import { ref, watch, computed, inject } from 'vue';

const t = inject('t');

const props = defineProps({
    sales: { type: Object, default: () => ({ data: [], links: [], meta: {} }) },
    filters: { type: Object, default: () => ({}) },
    grandTotal: { type: Number, default: 0 },
});

const search   = ref(props.filters?.search    || '');
const dateFrom = ref(props.filters?.date_from || '');
const dateTo   = ref(props.filters?.date_to   || '');

function todayStr() {
    return new Date().toISOString().slice(0, 10);
}
function mondayStr() {
    const d = new Date();
    const day = d.getDay();
    const diff = (day === 0 ? -6 : 1 - day);
    d.setDate(d.getDate() + diff);
    return d.toISOString().slice(0, 10);
}
function monthStartStr() {
    const d = new Date();
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-01`;
}

const activePeriod = computed(() => {
    const today = todayStr();
    if (dateFrom.value === today && dateTo.value === today) return 'today';
    if (dateFrom.value === mondayStr() && dateTo.value === today) return 'week';
    if (dateFrom.value === monthStartStr() && dateTo.value === today) return 'month';
    return null;
});

function setPeriod(period) {
    const today = todayStr();
    if (period === 'today') { dateFrom.value = today; dateTo.value = today; }
    else if (period === 'week')  { dateFrom.value = mondayStr();     dateTo.value = today; }
    else if (period === 'month') { dateFrom.value = monthStartStr(); dateTo.value = today; }
}

let searchTimer = null;
watch([search, dateFrom, dateTo], () => {
    clearTimeout(searchTimer);
    searchTimer = setTimeout(() => {
        router.get(route('sales.index'), {
            search:    search.value,
            date_from: dateFrom.value,
            date_to:   dateTo.value,
        }, { preserveState: true, replace: true });
    }, 400);
});

function formatCurrency(value) {
    return 'Rs. ' + Number(value || 0).toLocaleString('en-LK', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function formatDate(dateStr) {
    if (!dateStr) return '';
    return new Date(dateStr).toLocaleDateString('si-LK');
}

function formatTime(dateStr) {
    if (!dateStr) return '';
    return new Date(dateStr).toLocaleTimeString('en-LK', { hour: '2-digit', minute: '2-digit' });
}

const statusLabel = computed(() => ({
    completed: t('btn.complete'),
    pending: t('th.status'),
    cancelled: t('btn.cancel'),
    credit: t('lbl.credit'),
}));

const statusClass = {
    completed: 'bg-green-100 text-green-700',
    pending: 'bg-yellow-100 text-yellow-700',
    cancelled: 'bg-red-100 text-red-700',
    credit: 'bg-blue-100 text-blue-700',
};
</script>

<template>
    <Head :title="t('page.sales')" />

    <AuthenticatedLayout>
        <template #header>
            <div class="flex items-center justify-between">
                <h1 class="text-xl font-bold text-gray-800">{{ t('page.sales') }}</h1>
                <Link
                    :href="route('sales.create')"
                    class="inline-flex items-center bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors min-h-[44px]"
                >
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
                    </svg>
                    {{ t('btn.new_sale') }}
                </Link>
            </div>
        </template>

        <!-- Filters -->
        <div class="flex flex-col sm:flex-row gap-3 mb-4">
            <div class="flex-1 relative">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
                <input
                    v-model="search"
                    type="text"
                    :placeholder="t('lbl.invoice_no')"
                    class="w-full pl-10 pr-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 min-h-[44px]"
                />
            </div>
            <!-- Period chips -->
            <div class="flex items-center gap-1.5">
                <button
                    v-for="p in [{key:'today',label:t('lbl.today')},{key:'week',label:t('lbl.this_week')},{key:'month',label:t('lbl.this_month')}]"
                    :key="p.key"
                    type="button"
                    @click="setPeriod(p.key)"
                    class="px-3 py-2 rounded-lg text-sm font-semibold border transition-colors min-h-[44px]"
                    :class="activePeriod === p.key
                        ? 'bg-blue-600 text-white border-blue-600'
                        : 'bg-white text-gray-600 border-gray-300 hover:border-blue-400 hover:text-blue-600'"
                >{{ p.label }}</button>
            </div>
            <input
                v-model="dateFrom"
                type="date"
                class="border border-gray-300 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 min-h-[44px]"
            />
            <input
                v-model="dateTo"
                type="date"
                class="border border-gray-300 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 min-h-[44px]"
            />
        </div>

        <!-- Mobile cards -->
        <div class="md:hidden space-y-3 mb-4">
            <div v-if="sales.data?.length === 0" class="bg-white rounded-xl p-6 text-center text-gray-400">
                {{ t('lbl.no_data') }}
            </div>
            <div
                v-for="sale in sales.data"
                :key="sale.id"
                class="bg-white rounded-xl shadow-sm border border-gray-100 p-4"
            >
                <div class="flex justify-between items-start mb-2">
                    <div>
                        <p class="font-semibold text-gray-900">{{ sale.invoice_no }}</p>
                        <p class="text-sm text-gray-500">{{ sale.customer?.name || t('lbl.general') }}</p>
                        <p class="text-xs text-gray-400">{{ sale.user?.name }} · {{ formatDate(sale.created_at) }}</p>
                    </div>
                    <div class="text-right">
                        <p class="font-bold text-green-600">{{ formatCurrency(sale.total) }}</p>
                        <span
                            class="text-xs font-medium px-2 py-0.5 rounded-full"
                            :class="statusClass[sale.status] || 'bg-gray-100 text-gray-600'"
                        >
                            {{ statusLabel[sale.status] || sale.status }}
                        </span>
                    </div>
                </div>
                <Link
                    :href="route('sales.show', sale.id)"
                    class="block text-center bg-gray-50 hover:bg-gray-100 text-gray-600 py-2 rounded-lg text-sm font-medium transition-colors min-h-[44px] leading-[44px]"
                >
                    {{ t('btn.view') }}
                </Link>
            </div>
        </div>

        <!-- Desktop table -->
        <div class="hidden md:block bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden mb-4">
            <div class="overflow-x-auto">
                <table class="w-full">
                    <thead>
                        <tr class="text-left text-xs font-semibold text-gray-500 uppercase tracking-wider bg-gray-50 border-b border-gray-100">
                            <th class="px-4 py-3">{{ t('th.invoice') }}</th>
                            <th class="px-4 py-3">{{ t('lbl.customer') }}</th>
                            <th class="px-4 py-3">{{ t('th.total') }}</th>
                            <th class="px-4 py-3">{{ t('th.status') }}</th>
                            <th class="px-4 py-3">{{ t('lbl.cashier') }}</th>
                            <th class="px-4 py-3">{{ t('th.date') }}</th>
                            <th class="px-4 py-3 text-right">{{ t('th.actions') }}</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-100">
                        <tr v-if="sales.data?.length === 0">
                            <td colspan="7" class="px-4 py-8 text-center text-gray-400">{{ t('lbl.no_data') }}</td>
                        </tr>
                        <tr
                            v-for="sale in sales.data"
                            :key="sale.id"
                            class="hover:bg-gray-50 transition-colors"
                        >
                            <td class="px-4 py-3 font-medium text-blue-600">{{ sale.invoice_no }}</td>
                            <td class="px-4 py-3 text-gray-600">{{ sale.customer?.name || t('lbl.general') }}</td>
                            <td class="px-4 py-3 font-semibold text-green-600">{{ formatCurrency(sale.total) }}</td>
                            <td class="px-4 py-3">
                                <span
                                    class="text-xs font-medium px-2 py-1 rounded-full"
                                    :class="statusClass[sale.status] || 'bg-gray-100 text-gray-600'"
                                >
                                    {{ statusLabel[sale.status] || sale.status }}
                                </span>
                            </td>
                            <td class="px-4 py-3 text-gray-600">{{ sale.user?.name }}</td>
                            <td class="px-4 py-3 text-gray-500 text-sm">
                                {{ formatDate(sale.created_at) }}
                                <span class="text-gray-400">{{ formatTime(sale.created_at) }}</span>
                            </td>
                            <td class="px-4 py-3 text-right">
                                <Link
                                    :href="route('sales.show', sale.id)"
                                    class="text-blue-600 hover:text-blue-800 text-sm font-medium px-3 py-1.5 rounded hover:bg-blue-50 min-h-[36px] inline-flex items-center"
                                >
                                    {{ t('btn.view') }}
                                </Link>
                            </td>
                        </tr>
                    </tbody>
                    <!-- Total row -->
                    <tfoot v-if="sales.data?.length > 0">
                        <tr class="bg-gray-50 border-t-2 border-gray-200">
                            <td colspan="2" class="px-4 py-3 font-semibold text-gray-700">{{ t('lbl.total') }}</td>
                            <td class="px-4 py-3 font-bold text-green-700 text-lg">{{ formatCurrency(grandTotal) }}</td>
                            <td colspan="4"></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

        <!-- Mobile total -->
        <div v-if="sales.data?.length > 0" class="md:hidden bg-white rounded-xl shadow-sm border border-gray-100 p-4 mb-4 flex justify-between items-center">
            <span class="font-semibold text-gray-700">{{ t('lbl.total') }}</span>
            <span class="font-bold text-green-600 text-lg">{{ formatCurrency(grandTotal) }}</span>
        </div>

        <!-- Pagination -->
        <div v-if="sales.links?.length > 3" class="flex flex-wrap justify-center gap-1">
            <template v-for="link in sales.links" :key="link.label">
                <Link
                    v-if="link.url"
                    :href="link.url"
                    class="px-3 py-2 text-sm rounded-lg border transition-colors min-h-[44px] flex items-center"
                    :class="link.active ? 'bg-blue-600 text-white border-blue-600' : 'bg-white text-gray-600 border-gray-300 hover:bg-gray-50'"
                    v-html="link.label"
                />
                <span
                    v-else
                    class="px-3 py-2 text-sm rounded-lg border border-gray-200 text-gray-400 min-h-[44px] flex items-center"
                    v-html="link.label"
                />
            </template>
        </div>
    </AuthenticatedLayout>
</template>
