// pos-client/src/pages/sales/Show.jsx
import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate, useLocation } from 'react-router-dom';
import { useGetSaleQuery, useReturnSaleMutation } from '../../features/sales/salesApi';
import { useSelector } from 'react-redux';
import { selectCurrentUser, selectRole } from '../../features/auth/authSlice';
import { useLocale } from '../../contexts/LocaleContext';
import { translations } from '../../i18n/translations';
import { getApiUrl } from '../../config/runtimeConfig';

const API = getApiUrl();

const fmt = n => Number(n || 0).toLocaleString('en-LK', { minimumFractionDigits: 2 });
const fmtDate = s => new Date(s).toLocaleDateString('en-LK', { day: '2-digit', month: 'short', year: 'numeric' });
const fmtTime = s => new Date(s).toLocaleTimeString('en-LK', { hour: '2-digit', minute: '2-digit', hour12: true });

// ── Icons ─────────────────────────────────────────────────────────────────────
const IcoBack    = <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7"/></svg>;
const IcoReturn  = <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 10h10a8 8 0 0 1 8 8v2M3 10l6 6m-6-6l6-6"/></svg>;
const IcoPlus    = <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4"/></svg>;
const IcoRefresh = <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 0 0 4.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 0 1-15.357-2m15.357 2H15"/></svg>;
const IcoPrint   = <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 0 0 2-2v-4a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h2m2 4h6a2 2 0 0 0 2-2v-4a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2zm1-4h4v4H9v-4z"/></svg>;
const IcoSpinner = <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"/></svg>;
const IcoLogout  = <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3V7a3 3 0 0 1 3-3h4a3 3 0 0 1 3 3v1"/></svg>;

export default function SaleShow() {
  const { id }     = useParams();
  const navigate   = useNavigate();
  const location   = useLocation();
  const role       = useSelector(selectRole);
  const user       = useSelector(selectCurrentUser);
  const { t }      = useLocale();

  const { data: sale, isLoading, refetch } = useGetSaleQuery(id);
  const [returnSale, { isLoading: returning }] = useReturnSaleMutation();

  const [returnModal,  setReturnModal]  = useState(false);
  const [returnReason, setReturnReason] = useState('');
  const [returnItems,  setReturnItems]  = useState([]);
  const [paperSize,    setPaperSize]    = useState('80mm');
  const [shopInfo,     setShopInfo]     = useState({});
  const [printing,     setPrinting]     = useState(false);

  const autoPrintFiredRef = useRef(false);

  useEffect(() => {
    fetch(`${API}/api/settings/public`)
      .then(r => r.json())
      .then(setShopInfo)
      .catch(() => {});
  }, []);

  // Auto-print when arriving from POS via Enter key (autoPrint nav state)
  useEffect(() => {
    if (!location.state?.autoPrint) return;
    if (!sale || Object.keys(shopInfo).length === 0) return;
    if (autoPrintFiredRef.current) return;
    autoPrintFiredRef.current = true;
    handlePrint();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sale, shopInfo]);

  function openReturn() {
    setReturnItems((sale.items || []).map(i => ({ ...i, return_qty: 0 })));
    setReturnReason('');
    setReturnModal(true);
  }

  async function handleReturn(e) {
    e.preventDefault();
    const items = returnItems.filter(i => parseFloat(i.return_qty) > 0);
    if (!items.length) return;
    await returnSale({ id, reason: returnReason, items }).unwrap();
    setReturnModal(false);
    navigate('/sales');
  }

  async function handlePrint() {
    if (!sale || printing) return;
    setPrinting(true);
    const is80 = paperSize === '80mm';
    const currency = shopInfo.currency || 'Rs.';
    const receiptLang = shopInfo.receipt_language || 'en';
    const isSinhala = receiptLang === 'si';
    const rl = key => (translations[receiptLang] || translations.en)[key] ?? translations.en[key];
    const minDelay = new Promise(r => setTimeout(r, 2200));

    const itemsHtml = (sale.items || []).map((item, idx) => `
      <div class="item-row">
        <div class="item-name">${idx + 1} ${item.product_name}</div>
        <div class="item-total">${fmt(item.total)}</div>
      </div>
      <div class="item-sub">
        <span>${Number(item.qty)} × ${fmt(item.unit_price)}</span>
        ${parseFloat(item.discount) > 0 ? `<span class="disc-inline">- ${fmt(item.discount)}</span>` : ''}
      </div>
    `).join('');

    const payments  = sale.payments || [];
    const paidCash  = payments.filter(p => p.method === 'cash').reduce((s, p) => s + parseFloat(p.amount || 0), 0);
    const paidCard  = payments.filter(p => p.method === 'card').reduce((s, p) => s + parseFloat(p.amount || 0), 0);
    const paidCredit = payments.filter(p => p.method === 'credit').reduce((s, p) => s + parseFloat(p.amount || 0), 0);
    const change     = Math.max(0, parseFloat(sale.paid || 0) - parseFloat(sale.total || 0));
    const cashGiven  = paidCash + change;

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${sale.invoice_no}</title>
  ${isSinhala ? '<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Sinhala:wght@700;800;900&display=swap" rel="stylesheet">' : ''}
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    html, body {
      font-family: ${isSinhala ? "'Noto Sans Sinhala', sans-serif" : "'Courier New', Courier, monospace"};
      font-size: ${is80 ? '13px' : '15px'};
      font-weight: 900;
      width: ${is80 ? '80mm' : '210mm'};
      max-width: ${is80 ? '80mm' : '210mm'};
      color: #000;
      word-break: break-word;
      overflow-wrap: break-word;
    }
    body { padding: ${is80 ? '5mm 4mm' : '15mm 20mm'}; }
    .center { text-align:center; }
    .logo { width:${is80 ? '56px' : '72px'}; height:${is80 ? '56px' : '72px'}; object-fit:contain; margin:0 auto 6px; display:block; border-radius:50%; }
    .shop-name { font-size:${is80 ? '16px' : '22px'}; font-weight:900; text-align:center; text-transform:uppercase; letter-spacing:0.05em; margin-bottom:3px; color:#000; word-break:break-word; }
    .shop-meta { font-size:${is80 ? '12px' : '14px'}; font-weight:900; text-align:center; color:#000; line-height:1.6; word-break:break-word; }
    .divider { border:none; border-top:2px solid #000; margin:8px 0; }
    .row { display:flex; justify-content:space-between; gap:6px; padding:3px 0; font-size:${is80 ? '12px' : '14px'}; color:#000; }
    .row .label { color:#000; font-weight:900; flex-shrink:0; }
    .row .value { font-weight:900; color:#000; text-align:right; min-width:0; word-break:break-word; }
    .col-header { display:flex; justify-content:space-between; font-weight:900; padding:4px 0 3px; border-top:2px solid #000; border-bottom:2px solid #000; margin:6px 0; font-size:${is80 ? '12px' : '14px'}; color:#000; }
    .item-row { display:flex; justify-content:space-between; align-items:flex-start; gap:6px; font-weight:900; padding-top:5px; font-size:${is80 ? '13px' : '15px'}; color:#000; }
    .item-name { flex:1; min-width:0; word-break:break-word; overflow-wrap:break-word; }
    .item-total { flex-shrink:0; text-align:right; }
    .item-sub { display:flex; justify-content:space-between; padding-left:10px; color:#000; font-weight:900; padding-bottom:4px; font-size:${is80 ? '12px' : '13px'}; }
    .disc-inline { color:#000; font-weight:900; }
    .disc-box { border:2px solid #000; border-radius:4px; padding:3px 8px; display:flex; justify-content:space-between; gap:6px; margin:5px 0; }
    .disc-label { color:#000; font-weight:900; flex-shrink:0; }
    .disc-val { color:#000; font-weight:900; }
    .total-row { display:flex; justify-content:space-between; align-items:baseline; gap:6px; font-weight:900; font-size:${is80 ? '15px' : '20px'}; padding:6px 0 4px; border-top:2px solid #000; margin-top:4px; color:#000; }
    .total-val { color:#000; flex-shrink:0; }
    .paid-row { display:flex; justify-content:space-between; gap:6px; padding:3px 0; font-weight:900; font-size:${is80 ? '12px' : '14px'}; color:#000; }
    .change-row { display:flex; justify-content:space-between; gap:6px; font-weight:900; color:#000; padding:3px 0; font-size:${is80 ? '13px' : '15px'}; }
    .footer { text-align:center; margin-top:10px; font-size:${is80 ? '12px' : '14px'}; color:#000; font-weight:900; line-height:1.8; word-break:break-word; }
    @media print {
      html, body { overflow: visible !important; height: auto !important; }
      @page { margin: 0; size: ${is80 ? '80mm auto' : 'A4'}; }
      body { padding: ${is80 ? '3mm' : '10mm'}; width: ${is80 ? '80mm' : '210mm'} !important; }
    }
  </style>
</head>
<body>
  ${shopInfo.shop_logo ? `<img class="logo" src="${shopInfo.shop_logo}" alt="logo">` : ''}
  <div class="shop-name">${shopInfo.shop_name || 'LMUC POS'}</div>
  <div class="shop-meta">
    ${shopInfo.address ? shopInfo.address + '<br>' : ''}
    ${shopInfo.phone || ''}
  </div>
  <hr class="divider">
  <div class="row"><span class="label">${rl('th.invoice')}</span><span class="value">${sale.invoice_no}</span></div>
  <div class="row"><span class="label">${rl('th.date')}</span><span class="value">${fmtDate(sale.created_at)} ${fmtTime(sale.created_at)}</span></div>
  <div class="row"><span class="label">${rl('lbl.cashier')}</span><span class="value">${sale.user?.name || '—'}</span></div>
  ${sale.customer?.name ? `<div class="row"><span class="label">${rl('lbl.customer')}</span><span class="value">${sale.customer.name}</span></div>` : ''}
  <div class="col-header"><span># ${rl('th.product')}</span><span>${rl('th.total')}</span></div>
  ${itemsHtml}
  <hr class="divider">
  <div class="row"><span class="label">${rl('lbl.subtotal')}</span><span>${fmt(sale.subtotal)}</span></div>
  ${parseFloat(sale.discount) > 0 ? `<div class="disc-box"><span class="disc-label">${rl('lbl.discount')}</span><span class="disc-val">- ${fmt(sale.discount)}</span></div>` : ''}
  ${parseFloat(sale.tax) > 0 ? `<div class="row"><span class="label">${rl('lbl.tax')}</span><span>${fmt(sale.tax)}</span></div>` : ''}
  <div class="total-row"><span class="total-label">${rl('lbl.grand_total')}</span><span class="total-val">${currency} ${fmt(sale.total)}</span></div>
  ${paidCash > 0  ? `<div class="paid-row"><span>${rl('lbl.cash_paid')} (${rl('lbl.cash')})</span><span>${fmt(cashGiven)}</span></div>` : ''}
  ${paidCard > 0  ? `<div class="paid-row"><span>${rl('lbl.cash_paid')} (${rl('lbl.card')})</span><span>${fmt(paidCard)}</span></div>` : ''}
  ${paidCredit > 0 ? `<div class="paid-row"><span>${rl('lbl.credit')}</span><span>${fmt(paidCredit)}</span></div>` : ''}
  ${change > 0    ? `<div class="change-row"><span>${rl('lbl.change')}</span><span>${fmt(change)}</span></div>` : ''}
  <hr class="divider">
  <div class="footer">
    ${shopInfo.receipt_footer || 'Thank you for shopping with us!'}
    ${shopInfo.shop_name ? `<br>${(shopInfo.shop_name || '').toLowerCase().replace(/\s+/g, '') + '.lk'}` : ''}
  </div>
</body>
</html>`;

    try {
      // Electron: window.open() is blocked — print silently via IPC in a hidden window
      if (window.electronAPI?.printReceiptHtml) {
        const [r] = await Promise.all([
          window.electronAPI.printReceiptHtml(html, { paperSize }),
          minDelay,
        ]);
        if (r && !r.success) alert('Print failed: ' + (r.error || 'unknown error'));
      } else {
        // Browser: open popup and print
        const win = window.open('', '_blank', 'width=400,height=700,scrollbars=yes');
        if (win) {
          win.document.write(html);
          win.document.close();
          win.onload = () => win.print();
        }
        await minDelay;
      }
    } catch (err) {
      alert('Print error: ' + err.message);
    } finally {
      setPrinting(false);
      if (location.state?.autoPrint) {
        navigate('/sales/create', { replace: true });
      }
    }
  }

  const roleColor = { admin: 'bg-red-500', manager: 'bg-blue-500', cashier: 'bg-green-500' };
  const payments   = sale?.payments || [];
  const paidCash   = payments.filter(p => p.method === 'cash').reduce((s, p) => s + parseFloat(p.amount || 0), 0);
  const paidCard   = payments.filter(p => p.method === 'card').reduce((s, p) => s + parseFloat(p.amount || 0), 0);
  const paidCredit = payments.filter(p => p.method === 'credit').reduce((s, p) => s + parseFloat(p.amount || 0), 0);
  const change     = Math.max(0, parseFloat(sale?.paid || 0) - parseFloat(sale?.total || 0));
  const cashGiven  = paidCash + change;
  const currency   = shopInfo.currency || 'Rs.';

  if (isLoading) return (
    <div className="h-screen flex items-center justify-center text-slate-400 text-sm">{t('lbl.loading')}</div>
  );
  if (!sale) return (
    <div className="h-screen flex items-center justify-center text-slate-400 text-sm">Sale not found</div>
  );

  return (
    <div className="flex flex-col h-full bg-slate-100">

      {/* ── Custom top bar ──────────────────────────────────────────────── */}
      <header className="bg-white border-b border-slate-200 shadow-sm px-3 py-2 flex items-center justify-between sticky top-0 z-10 gap-2">
        <div className="flex items-center gap-2 min-w-0 shrink">
          <button onClick={() => navigate('/sales')}
            className="p-1.5 rounded-lg text-slate-500 hover:text-slate-700 hover:bg-slate-100 transition-colors shrink-0">
            {IcoBack}
          </button>
          <span className="font-bold text-slate-800 font-mono text-xs sm:text-sm truncate">{sale.invoice_no}</span>
          {sale.status === 'returned' && (
            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-red-100 text-red-600 uppercase tracking-wide shrink-0">{t('btn.return')}</span>
          )}
        </div>

        <div className="flex items-center gap-1.5 shrink-0">
          {/* Paper size toggle */}
          <div className="flex rounded-lg border border-slate-200 overflow-hidden text-xs font-semibold">
            <button onClick={() => setPaperSize('80mm')}
              className={`px-2 py-1.5 transition-colors ${paperSize === '80mm' ? 'bg-slate-700 text-white' : 'bg-white text-slate-600 hover:bg-slate-50'}`}>
              80mm
            </button>
            <button onClick={() => setPaperSize('A4')}
              className={`px-2 py-1.5 transition-colors border-l border-slate-200 ${paperSize === 'A4' ? 'bg-slate-700 text-white' : 'bg-white text-slate-600 hover:bg-slate-50'}`}>
              A4
            </button>
          </div>

          {/* Return button */}
          {sale.status === 'completed' && (role === 'admin' || role === 'manager') && (
            <button onClick={openReturn}
              className="flex items-center gap-1 px-2 py-1.5 rounded-lg border border-red-300 text-red-600 text-xs font-semibold hover:bg-red-50 transition-colors">
              {IcoReturn}
              <span className="hidden sm:inline">{t('btn.return')}</span>
            </button>
          )}

          {/* New Sale */}
          <button onClick={() => navigate('/sales/create')}
            className="flex items-center gap-1 px-2 py-1.5 rounded-lg bg-green-500 text-white text-xs font-semibold hover:bg-green-600 transition-colors">
            {IcoPlus}
            <span className="hidden sm:inline">{t('btn.new_sale')}</span>
          </button>

          {/* Refresh */}
          <button onClick={refetch}
            className="p-1.5 rounded-lg text-slate-500 hover:text-slate-700 hover:bg-slate-100 transition-colors">
            {IcoRefresh}
          </button>

          <div className="w-px h-5 bg-slate-200 hidden sm:block" />

          {/* User avatar */}
          <div className={`w-7 h-7 rounded-full ${roleColor[role] || 'bg-slate-500'} flex items-center justify-center text-white font-bold text-xs shrink-0`}>
            {user?.name?.[0]?.toUpperCase() || 'U'}
          </div>
          <div className="text-xs leading-tight hidden md:block">
            <p className="font-semibold text-slate-700">{user?.name}</p>
            <p className="text-slate-400 capitalize">{role}</p>
          </div>
        </div>
      </header>

      {/* ── Print button ────────────────────────────────────────────────── */}
      <button onClick={handlePrint} disabled={printing}
        className="fixed bottom-4 right-4 sm:bottom-6 sm:right-6 z-20 flex items-center gap-2 px-4 sm:px-6 py-2.5 sm:py-3 rounded-full bg-blue-600 text-white font-semibold text-sm hover:bg-blue-700 disabled:opacity-70 disabled:cursor-not-allowed transition-all shadow-lg shadow-blue-600/40">
        {printing ? IcoSpinner : IcoPrint}
        <span>{printing ? t('lbl.loading') : t('btn.print')}</span>
      </button>

      {/* ── Scrollable receipt area ──────────────────────────────────────── */}
      <div className="flex-1 overflow-y-auto py-6 sm:py-8 px-3 sm:px-4 flex flex-col items-center pb-20">

        {/* Receipt card */}
        <div id="receipt"
          className="bg-white rounded-2xl shadow-md border border-slate-100 w-full max-w-sm px-8 py-7"
          style={{ fontFamily: "'Outfit', 'Noto Sans Sinhala', sans-serif" }}>

          {/* Shop header */}
          <div className="text-center mb-5">
            {shopInfo.shop_logo ? (
              <img src={shopInfo.shop_logo} alt="logo"
                className="w-24 h-24 object-contain mx-auto mb-3 rounded-full" />
            ) : (
              <div className="w-24 h-24 bg-slate-100 rounded-full mx-auto mb-3 flex items-center justify-center text-slate-400 text-4xl font-black">
                {(shopInfo.shop_name || 'L')[0]}
              </div>
            )}
            <p className="font-black text-slate-900 text-xl tracking-wide uppercase">
              {shopInfo.shop_name || 'LMUC POS'}
            </p>
            {shopInfo.address && <p className="text-slate-500 text-sm font-medium mt-0.5">{shopInfo.address}</p>}
            {shopInfo.phone   && <p className="text-slate-500 text-sm font-medium">{shopInfo.phone}</p>}
          </div>

          <hr className="border-slate-200 mb-4" />

          {/* Invoice meta */}
          <div className="space-y-1.5">
            <MetaRow label={t('th.invoice')}  value={sale.invoice_no} mono />
            <MetaRow label={t('th.date')}     value={`${fmtDate(sale.created_at)} ${fmtTime(sale.created_at)}`} />
            <MetaRow label={t('lbl.cashier')} value={sale.user?.name || '—'} />
            {sale.customer?.name && <MetaRow label={t('lbl.customer')} value={sale.customer.name} />}
          </div>

          <hr className="border-slate-200 my-4" />

          {/* Items */}
          <div className="mb-3">
            <div className="flex justify-between text-sm font-black text-slate-700 border-b-2 border-slate-200 pb-2 mb-3">
              <span># {t('th.product')}</span>
              <span>{t('th.total')}</span>
            </div>
            {(sale.items || []).map((item, idx) => (
              <div key={item.id} className="mb-3">
                <div className="flex justify-between text-sm font-bold text-slate-900">
                  <span>{idx + 1} {item.product_name}</span>
                  <span>{fmt(item.total)}</span>
                </div>
                <div className="flex justify-between text-sm text-slate-400 font-medium pl-4 mt-0.5">
                  <span>{Number(item.qty)} × {fmt(item.unit_price)}</span>
                  {parseFloat(item.discount) > 0 && (
                    <span className="text-red-400">- {fmt(item.discount)}</span>
                  )}
                </div>
              </div>
            ))}
          </div>

          <hr className="border-slate-200 mb-4" />

          {/* Totals */}
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span className="text-slate-500 font-semibold">{t('lbl.subtotal')}</span>
              <span className="font-bold text-slate-700">{fmt(sale.subtotal)}</span>
            </div>

            {parseFloat(sale.discount) > 0 && (
              <div className="flex justify-between items-center border-2 border-blue-300 rounded-lg px-3 py-1.5 bg-blue-50">
                <span className="text-blue-700 font-bold text-sm">{t('lbl.discount')}</span>
                <span className="text-red-500 font-extrabold text-sm">- {fmt(sale.discount)}</span>
              </div>
            )}

            {parseFloat(sale.tax) > 0 && (
              <div className="flex justify-between text-sm">
                <span className="text-slate-500 font-semibold">{t('lbl.tax')}</span>
                <span className="font-bold text-slate-700">{fmt(sale.tax)}</span>
              </div>
            )}

            <div className="flex justify-between items-baseline pt-1 border-t border-slate-100">
              <span className="text-base font-black text-slate-900">{t('lbl.grand_total')}</span>
              <span className="text-xl font-black text-blue-600">{currency} {fmt(sale.total)}</span>
            </div>

            {paidCash   > 0 && (
              <div className="flex justify-between text-sm">
                <span className="text-slate-500 font-semibold">{t('lbl.cash_paid')} ({t('lbl.cash')})</span>
                <span className="font-bold text-slate-700">{fmt(cashGiven)}</span>
              </div>
            )}
            {paidCard   > 0 && (
              <div className="flex justify-between text-sm">
                <span className="text-slate-500 font-semibold">{t('lbl.cash_paid')} ({t('lbl.card')})</span>
                <span className="font-bold text-slate-700">{fmt(paidCard)}</span>
              </div>
            )}
            {paidCredit > 0 && (
              <div className="flex justify-between text-sm">
                <span className="text-slate-500 font-semibold">{t('lbl.credit')}</span>
                <span className="font-bold text-red-500">{fmt(paidCredit)}</span>
              </div>
            )}
            {change > 0 && (
              <div className="flex justify-between text-sm font-bold text-green-600">
                <span>{t('lbl.change')}</span>
                <span>{fmt(change)}</span>
              </div>
            )}
          </div>

          <hr className="border-slate-200 my-5" />

          {/* Footer */}
          <div className="text-center leading-relaxed">
            <p className="text-sm font-semibold text-slate-500">
              {shopInfo.receipt_footer || 'Thank you for shopping with us!'}
            </p>
            {shopInfo.shop_name && (
              <p className="text-blue-500 font-bold text-sm mt-1">
                {shopInfo.shop_name.toLowerCase().replace(/\s+/g, '') + '.lk'}
              </p>
            )}
          </div>
        </div>

      </div>

      {/* ── Return modal ────────────────────────────────────────────────── */}
      {returnModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-lg p-6 space-y-4 max-h-[90vh] overflow-y-auto mx-4">
            <div className="flex items-center justify-between">
              <h2 className="text-base font-bold text-slate-800">{t('btn.return')}</h2>
              <span className="font-mono text-xs text-slate-400">{sale.invoice_no}</span>
            </div>
            <form onSubmit={handleReturn} className="space-y-4">
              <div>
                <label className="block text-xs font-semibold text-slate-600 mb-1.5">Reason for return</label>
                <input value={returnReason} onChange={e => setReturnReason(e.target.value)} required
                  placeholder="Enter reason..."
                  className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-600 mb-1.5">Select items to return</label>
                <div className="rounded-xl border border-slate-100 overflow-hidden">
                  <table className="w-full text-sm">
                    <thead className="bg-slate-50">
                      <tr>
                        <th className="text-left px-3 py-2 text-xs font-semibold text-slate-500">{t('th.product')}</th>
                        <th className="text-right px-3 py-2 text-xs font-semibold text-slate-500">{t('th.qty')}</th>
                        <th className="text-right px-3 py-2 text-xs font-semibold text-slate-500">Return Qty</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-50">
                      {returnItems.map((item, i) => (
                        <tr key={item.id}>
                          <td className="px-3 py-2 text-slate-700">{item.product_name}</td>
                          <td className="px-3 py-2 text-right text-slate-500">{item.qty}</td>
                          <td className="px-3 py-2 text-right">
                            <input type="number" min="0" max={item.qty} step="0.001"
                              value={item.return_qty}
                              onChange={e => {
                                const v = e.target.value;
                                setReturnItems(ri => ri.map((r, idx) => idx === i ? { ...r, return_qty: v } : r));
                              }}
                              className="w-24 rounded-lg border border-slate-200 px-2 py-1 text-sm text-right outline-none focus:ring-1 focus:ring-blue-500" />
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-1">
                <button type="button" onClick={() => setReturnModal(false)}
                  className="px-4 py-2 rounded-xl border border-slate-200 text-sm text-slate-600 hover:bg-slate-50 transition-colors">
                  {t('btn.cancel')}
                </button>
                <button type="submit" disabled={returning}
                  className="px-4 py-2 rounded-xl bg-red-600 text-white text-sm font-semibold disabled:opacity-60 hover:bg-red-700 transition-colors">
                  {returning ? t('lbl.loading') : t('btn.return')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

function MetaRow({ label, value, mono }) {
  return (
    <div className="flex justify-between text-sm">
      <span className="text-slate-500 font-semibold">{label}</span>
      <span className={`font-bold text-slate-800 ${mono ? 'font-mono' : ''}`}>{value}</span>
    </div>
  );
}

// resources/js/Pages/Sales/Show.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link } from '@inertiajs/vue3';
import { router } from '@inertiajs/vue3';
import { ref, computed, inject, onMounted } from 'vue';

const t     = inject('t');
const tBill = inject('tBill');

const props = defineProps({
    sale:     { type: Object, required: true },
    settings: { type: Object, default: () => ({}) },
});

const shopName    = computed(() => props.settings.shop_name    || 'LUMAC POS');
const shopAddress = computed(() => props.settings.shop_address || '');
const shopPhone   = computed(() => props.settings.shop_phone   || '');
const footer      = computed(() => props.settings.receipt_footer || '');
const currency    = computed(() => props.settings.currency     || 'Rs.');
const logoUrl     = computed(() => props.settings.logo_url     || null);

const paymentLabel = computed(() => {
    const map = { cash: tBill('lbl.cash'), card: tBill('lbl.card'), qr: 'QR', credit: tBill('lbl.credit') };
    return props.sale.payments?.[0]
        ? (map[props.sale.payments[0].method] || props.sale.payments[0].method)
        : '';
});

function fmtDate(d) {
    if (!d) return '';
    return new Date(d).toLocaleDateString('si-LK', { year: 'numeric', month: 'long', day: 'numeric' });
}

function fmtTime(d) {
    if (!d) return '';
    return new Date(d).toLocaleTimeString('en-LK', { hour: '2-digit', minute: '2-digit' });
}

function n(val) {
    return Number(val || 0).toFixed(2);
}

const profit = computed(() => {
    if (!props.sale.items?.length) return 0;
    return props.sale.items.reduce((sum, item) => {
        const revenue = Number(item.total || 0);
        const cost    = Number(item.cost_price || 0) * Number(item.qty || 0);
        return sum + (revenue - cost);
    }, 0);
});

async function printReceipt() {
    if (printing.value) return;
    printing.value = true;
    try {
        if (window.electronAPI?.isElectron) {
            const printer = localStorage.getItem('pos_printer') || '';
            const result  = await window.electronAPI.printReceipt(printer);
            if (!result?.success) {
                console.error('[print-receipt] failed:', result?.error);
                window.print();
            }
        } else {
            window.print();
        }
    } finally {
        setTimeout(() => { printing.value = false; }, 3000);
    }
}

const isElectron = !!window.electronAPI?.isElectron;
const printing   = ref(false);

onMounted(async () => {
    const params = new URLSearchParams(window.location.search);
    if (params.get('autoPrint') === '1') {
        await printReceipt();
        router.visit(route('sales.create'));
    }
});
</script>

<template>
    <Head :title="`${t('lbl.invoice_no')} ${sale.invoice_no}`" />

    <AuthenticatedLayout>
        <template #header>
            <div class="flex items-center gap-3">
                <Link :href="route('sales.index')" class="text-slate-400 hover:text-slate-600">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                    </svg>
                </Link>
                <h1 class="text-xl font-bold" style="color:#0F172A;">{{ sale.invoice_no }}</h1>
                <div class="ml-auto flex gap-2">
                    <Link
                        :href="route('sales.create')"
                        class="flex items-center gap-2 text-white px-4 py-2 rounded-lg text-sm font-semibold"
                        style="background-color:#16A34A;"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
                        </svg>
                        {{ t('btn.new_sale') }}
                    </Link>
                </div>
            </div>
        </template>

        <!-- Print button — fixed top-right -->
        <button
            type="button"
            @click="printReceipt"
            :disabled="printing"
            title="Print"
            class="no-print print-btn fixed z-50 flex items-center gap-2 text-white rounded-full shadow-lg overflow-hidden transition-all"
            :style="`top:72px; right:24px; height:44px; padding:0 16px 0 14px; background-color:${printing ? '#6B7280' : '#2563EB'}; cursor:${printing ? 'not-allowed' : 'pointer'};`"
        >
            <!-- Spinner while printing -->
            <svg v-if="printing" class="h-5 w-5 shrink-0 animate-spin" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"/>
            </svg>
            <!-- Printer icon normally -->
            <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            <span class="print-label text-sm font-semibold">{{ printing ? 'Printing…' : t('btn.print') }}</span>
        </button>

        <!-- Receipt centred on screen -->
        <div id="receipt-wrapper" class="flex flex-col items-center py-6 gap-4">
            <div id="receipt-card" class="bg-white rounded-xl shadow-sm p-8" style="border:1px solid #E2E8F0; width:340px;">

                <!-- Shop header -->
                <div class="text-center mb-4">
                    <img
                        v-if="logoUrl"
                        :src="logoUrl"
                        alt="Logo"
                        class="receipt-logo mx-auto mb-2 object-contain"
                        style="max-height:64px; max-width:180px;"
                    />
                    <p class="shop-title font-extrabold text-[16px]" style="color:#0F172A; letter-spacing:0.01em;">{{ shopName }}</p>
                    <p v-if="shopAddress" class="text-[12px] font-bold" style="color:#334155;">{{ shopAddress }}</p>
                    <p v-if="shopPhone" class="text-[12px] font-bold" style="color:#334155;">{{ shopPhone }}</p>
                </div>

                <div class="divider" style="border-top:1px dashed #CBD5E1; margin:10px 0;"></div>

                <!-- Invoice meta -->
                <div class="text-[12px] space-y-1 mb-1 font-bold" style="color:#1E293B;">
                    <div class="flex justify-between">
                        <span>{{ tBill('th.invoice') }}</span>
                        <span class="font-extrabold">{{ sale.invoice_no }}</span>
                    </div>
                    <div class="flex justify-between">
                        <span>{{ tBill('th.date') }}</span>
                        <span>{{ fmtDate(sale.created_at) }}</span>
                    </div>
                    <div class="flex justify-between">
                        <span>{{ tBill('th.time') }}</span>
                        <span>{{ fmtTime(sale.created_at) }}</span>
                    </div>
                    <div class="flex justify-between">
                        <span>{{ tBill('lbl.cashier') }}</span>
                        <span>{{ sale.user?.name }}</span>
                    </div>
                    <div v-if="sale.customer" class="flex justify-between">
                        <span>{{ tBill('lbl.customer') }}</span>
                        <span>{{ sale.customer.name }}</span>
                    </div>
                </div>

                <div class="items-section divider" style="border-top:1px dashed #CBD5E1; margin:10px 0;"></div>

                <!-- Items -->
                <table class="items-section" style="width:100%; border-collapse:collapse; font-size:12px; color:#0F172A; font-weight:800;">
                    <thead>
                        <tr style="border-bottom:2px solid #CBD5E1;">
                            <th style="text-align:left; width:16px; padding:4px 4px 4px 0; font-weight:800;">#</th>
                            <th style="text-align:left; padding:4px 8px 4px 0; font-weight:800;">{{ tBill('th.product') }}</th>
                            <th style="text-align:center; width:28px; padding:4px 0; font-weight:800;">{{ tBill('th.qty') }}</th>
                            <th style="text-align:right; width:52px; padding:4px 0; font-weight:800;">{{ tBill('th.price') }}</th>
                            <th style="text-align:right; width:48px; padding:4px 0; font-weight:800; color:#D97706;">{{ tBill('lbl.discount') }}</th>
                            <th style="text-align:right; width:56px; padding:4px 0; font-weight:800;">{{ tBill('lbl.total') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        <template v-for="(item, index) in sale.items" :key="item.id">
                            <!-- Line 1: item number + product names -->
                            <tr>
                                <td style="padding:4px 4px 0 0; font-weight:800; vertical-align:top;">{{ index + 1 }}</td>
                                <td colspan="5" style="padding:4px 8px 0 0; word-break:break-word; font-weight:800; color:#0F172A;">
                                    <span>{{ item.product_name?.split(' / ')[0] ?? item.product_name }}</span>
                                    <span v-if="item.product?.name_si" style="font-size:11px; font-weight:800; color:#334155;"> / {{ item.product.name_si }}</span>
                                </td>
                            </tr>
                            <!-- Line 2: qty / price / discount / total -->
                            <tr style="border-bottom:1px dashed #CBD5E1;">
                                <td style="padding:0 0 5px 0;"></td>
                                <td style="padding:0 0 5px 0;"></td>
                                <td style="text-align:center; padding:0 0 5px 0; font-weight:800;">{{ item.qty }}</td>
                                <td style="text-align:right; padding:0 0 5px 0; font-weight:800;">{{ n(item.unit_price) }}</td>
                                <td style="text-align:right; padding:0 0 5px 0; color:#D97706; font-weight:800;">{{ Number(item.discount) > 0 ? n(item.discount) : '-' }}</td>
                                <td style="text-align:right; padding:0 0 5px 0; font-weight:800; color:#0F172A;">{{ n(item.total) }}</td>
                            </tr>
                        </template>
                    </tbody>
                </table>

                <div class="items-section divider" style="border-top:1px dashed #CBD5E1; margin:10px 0;"></div>

                <!-- Totals -->
                <div class="space-y-1.5 text-[12px] font-bold" style="color:#0F172A;">
                    <div class="flex justify-between">
                        <span>{{ tBill('lbl.subtotal') }}</span>
                        <span>{{ n(sale.subtotal) }}</span>
                    </div>
                    <div v-if="Number(sale.discount) > 0" class="flex justify-between" style="color:#D97706;">
                        <span>{{ tBill('lbl.discount') }}</span>
                        <span>-{{ n(sale.discount) }}</span>
                    </div>
                    <div class="total-row flex justify-between text-[15px] pt-2" style="color:#0F172A; border-top:2px solid #0F172A; font-weight:800;">
                        <span>{{ tBill('lbl.total') }}</span>
                        <span style="color:#2563EB;">{{ currency }} {{ n(sale.total) }}</span>
                    </div>
                    <div class="flex justify-between" style="color:#16A34A;">
                        <span>{{ tBill('th.paid') }} ({{ paymentLabel }})</span>
                        <span>{{ n(sale.payments?.[0]?.amount) }}</span>
                    </div>
                    <div v-if="Number(sale.balance) < 0" class="flex justify-between">
                        <span>{{ tBill('lbl.change') }}</span>
                        <span>{{ n(Math.abs(sale.balance)) }}</span>
                    </div>
                </div>

                <div class="divider" style="border-top:1px dashed #CBD5E1; margin:10px 0;"></div>

                <!-- Footer -->
                <p class="text-center font-extrabold text-[13px]" style="color:#0F172A; white-space: pre-line;">{{ footer }}</p>

                <p class="text-center font-extrabold text-[11px] mt-3" style="color:#0F172A;">lunac.lk</p>
            </div>

        </div>
    </AuthenticatedLayout>
</template>

<style>
/* Print button pulse + label slide-in */
.print-btn {
    transition: box-shadow 0.2s, transform 0.2s;
    animation: print-pulse 2.5s ease-in-out infinite;
}
.print-btn:hover {
    transform: scale(1.06);
    box-shadow: 0 6px 20px rgba(37,99,235,0.45);
    animation: none;
}
.print-btn:active {
    transform: scale(0.96);
}
.print-label {
    display: inline-block;
    animation: label-slide 2.5s ease-in-out infinite;
}
@keyframes print-pulse {
    0%, 100% { box-shadow: 0 4px 14px rgba(37,99,235,0.35); }
    50%       { box-shadow: 0 4px 22px rgba(37,99,235,0.65); }
}
@keyframes label-slide {
    0%, 80%, 100% { opacity: 1; transform: translateX(0); }
    90%            { opacity: 0.6; transform: translateX(3px); }
}

@media print {
    @page {
        size: 80mm auto;
        margin: 0;
    }

    /* Hide entire page, then reveal only the receipt */
    html, body {
        margin: 0 !important;
        padding: 0 !important;
        width: 80mm !important;
    }

    body * {
        visibility: hidden !important;
    }

    #receipt-wrapper,
    #receipt-card,
    #receipt-card * {
        visibility: visible !important;
    }

    /* Pin wrapper to top-left, no gaps */
    #receipt-wrapper {
        position: fixed !important;
        top: 0 !important;
        left: 0 !important;
        width: 80mm !important;
        margin: 0 !important;
        padding: 0 !important;
        display: block !important;
    }

    /* Receipt card fills exactly 80mm */
    #receipt-card {
        position: static !important;
        width: 80mm !important;
        max-width: 80mm !important;
        padding: 4mm 5mm !important;
        margin: 0 !important;
        border: none !important;
        box-shadow: none !important;
        border-radius: 0 !important;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
    }

    #receipt-card * {
        font-weight: 800 !important;
    }

    #receipt-card .shop-title {
        font-size: 16px !important;
        font-weight: 800 !important;
    }

    #receipt-card .total-row,
    #receipt-card .total-row span {
        font-size: 15px !important;
        font-weight: 800 !important;
    }

    #receipt-card .divider {
        border-top: 1px dashed #555 !important;
        margin: 5px 0 !important;
    }

    #receipt-card .receipt-logo {
        max-height: 56px !important;
        max-width: 160px !important;
    }
}
</style>
