// pos-client/src/pages/invoices/Show.jsx
import { useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { useGetSaleQuery, useMarkSalePaidMutation } from '../../features/sales/salesApi';
import { api } from '../../app/baseApi';
import { useSelector } from 'react-redux';
import { selectToken } from '../../features/auth/authSlice';

const settingsApi = api.injectEndpoints({
  endpoints: b => ({
    getInvoiceSettings: b.query({ query: () => '/settings', providesTags: ['Settings'] }),
  }),
  overrideExisting: false,
});

const fmt     = n => Number(n || 0).toLocaleString('en-LK', { minimumFractionDigits: 2 });
const fmtDate = s => s ? new Date(s).toLocaleDateString('en-LK', { year: 'numeric', month: 'long', day: 'numeric' }) : '—';

export default function InvoiceShow() {
  const { id }    = useParams();
  const navigate  = useNavigate();
  const { data: sale, isLoading } = useGetSaleQuery(id);
  const [markPaid, { isLoading: marking }] = useMarkSalePaidMutation();
  const [markErr, setMarkErr] = useState('');
  const token = useSelector(selectToken);

  async function handleMarkPaid() {
    setMarkErr('');
    try { await markPaid(id).unwrap(); }
    catch (e) { setMarkErr(e?.data?.error || 'Failed'); }
  }
  const { data: rawSettings } = settingsApi.useGetInvoiceSettingsQuery(undefined, { skip: !token });

  const shop = {
    name:    rawSettings?.shop_name    || '',
    address: rawSettings?.address      || '',
    phone:   rawSettings?.phone        || '',
    email:   rawSettings?.email        || '',
  };


  if (isLoading) return (
    <div className="flex items-center justify-center h-64 text-slate-400">Loading…</div>
  );
  if (!sale) return (
    <div className="flex items-center justify-center h-64 text-slate-400">Invoice not found</div>
  );

  const items    = sale.items || [];
  const payments = sale.payments || [];
  const subtotal = items.reduce((s, i) => s + parseFloat(i.unit_price) * parseFloat(i.qty), 0);
  const totalDisc= items.reduce((s, i) => s + parseFloat(i.discount || 0), 0);

  return (
    <>
      {/* Screen toolbar — hidden when printing */}
      <div className="print:hidden flex items-center gap-3 p-4 bg-white border-b border-slate-200 sticky top-0 z-10">
        <button onClick={() => navigate('/invoices')}
          className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition-colors">
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7"/>
          </svg>
        </button>
        <h1 className="font-bold text-slate-800 flex-1">Invoice {sale.invoice_no}</h1>
        {parseFloat(sale.balance) > 0 && (
          <div className="flex items-center gap-2">
            {markErr && <span className="text-xs text-red-500">{markErr}</span>}
            <button onClick={handleMarkPaid} disabled={marking}
              className="flex items-center gap-1.5 px-4 py-2 bg-green-600 text-white text-sm font-semibold rounded-lg hover:bg-green-700 transition-colors disabled:opacity-60">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7"/>
              </svg>
              {marking ? 'Saving…' : 'Mark as Paid'}
            </button>
          </div>
        )}
        {parseFloat(sale.balance) <= 0 && payments.some(p => p.method === 'credit') && (
          <span className="px-3 py-1.5 rounded-lg bg-green-100 text-green-700 text-xs font-bold">Paid</span>
        )}
        <Link to={`/invoices/create`}
          className="px-4 py-2 border border-slate-200 text-sm font-semibold text-slate-600 rounded-lg hover:bg-slate-50 transition-colors">
          New Invoice
        </Link>
        <button onClick={() => window.print()}
          className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white text-sm font-semibold rounded-lg hover:bg-blue-700 transition-colors">
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/>
          </svg>
          Print
        </button>
      </div>

      {/* A4 invoice — centered on screen, full width when printing */}
      <div className="print:m-0 print:p-0 bg-slate-100 print:bg-white min-h-screen py-8 print:py-0">
        <div
          id="invoice-a4"
          className="bg-white mx-auto print:mx-0 print:shadow-none shadow-xl"
          style={{ width: '210mm', minHeight: '297mm', padding: '15mm 18mm', boxSizing: 'border-box', fontFamily: 'Arial, sans-serif' }}>

          {/* Company header */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '10mm', borderBottom: '2px solid #1e293b', paddingBottom: '6mm' }}>
            <div>
              <div style={{ fontSize: '22pt', fontWeight: 'bold', color: '#1e293b', lineHeight: 1.2 }}>{shop.name}</div>
              {shop.address && <div style={{ fontSize: '9pt', color: '#64748b', marginTop: '2mm' }}>{shop.address}</div>}
              {shop.phone   && <div style={{ fontSize: '9pt', color: '#64748b' }}>Tel: {shop.phone}</div>}
              {shop.email   && <div style={{ fontSize: '9pt', color: '#64748b' }}>{shop.email}</div>}
            </div>
            <div style={{ textAlign: 'right' }}>
              <div style={{ fontSize: '20pt', fontWeight: 'bold', color: '#2563eb', letterSpacing: '1px' }}>INVOICE</div>
              <div style={{ fontSize: '11pt', fontWeight: 'bold', color: '#1e293b', marginTop: '2mm' }}>{sale.invoice_no}</div>
              <div style={{ fontSize: '9pt', color: '#64748b', marginTop: '1mm' }}>Date: {fmtDate(sale.created_at)}</div>
            </div>
          </div>

          {/* Bill to */}
          {sale.customer && (
            <div style={{ marginBottom: '8mm' }}>
              <div style={{ fontSize: '8pt', fontWeight: 'bold', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '2mm' }}>Bill To</div>
              <div style={{ fontSize: '11pt', fontWeight: 'bold', color: '#1e293b' }}>{sale.customer.name}</div>
              {sale.customer.phone && <div style={{ fontSize: '9pt', color: '#64748b' }}>{sale.customer.phone}</div>}
            </div>
          )}

          {/* Line items table */}
          <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '8mm', fontSize: '9.5pt' }}>
            <thead>
              <tr style={{ backgroundColor: '#1e293b', color: 'white' }}>
                <th style={{ padding: '2.5mm 3mm', textAlign: 'left', fontWeight: 'bold', width: '8mm' }}>#</th>
                <th style={{ padding: '2.5mm 3mm', textAlign: 'left', fontWeight: 'bold' }}>Description</th>
                <th style={{ padding: '2.5mm 3mm', textAlign: 'right', fontWeight: 'bold', width: '20mm' }}>Qty</th>
                <th style={{ padding: '2.5mm 3mm', textAlign: 'right', fontWeight: 'bold', width: '28mm' }}>Unit Price</th>
                <th style={{ padding: '2.5mm 3mm', textAlign: 'right', fontWeight: 'bold', width: '22mm' }}>Disc</th>
                <th style={{ padding: '2.5mm 3mm', textAlign: 'right', fontWeight: 'bold', width: '28mm' }}>Amount</th>
              </tr>
            </thead>
            <tbody>
              {items.map((item, i) => (
                <tr key={item.id} style={{ backgroundColor: i % 2 === 0 ? '#f8fafc' : 'white', borderBottom: '1px solid #e2e8f0' }}>
                  <td style={{ padding: '2.5mm 3mm', color: '#94a3b8' }}>{i + 1}</td>
                  <td style={{ padding: '2.5mm 3mm', fontWeight: '500', color: '#1e293b' }}>{item.product_name}</td>
                  <td style={{ padding: '2.5mm 3mm', textAlign: 'right', color: '#475569' }}>{parseFloat(item.qty)}</td>
                  <td style={{ padding: '2.5mm 3mm', textAlign: 'right', color: '#475569' }}>{fmt(item.unit_price)}</td>
                  <td style={{ padding: '2.5mm 3mm', textAlign: 'right', color: '#ef4444' }}>
                    {parseFloat(item.discount) > 0 ? fmt(item.discount) : '—'}
                  </td>
                  <td style={{ padding: '2.5mm 3mm', textAlign: 'right', fontWeight: 'bold', color: '#1e293b' }}>{fmt(item.total)}</td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* Totals */}
          <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: '10mm' }}>
            <div style={{ minWidth: '80mm', fontSize: '9.5pt' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '1.5mm 0', borderBottom: '1px solid #e2e8f0', color: '#64748b' }}>
                <span>Subtotal</span>
                <span>Rs. {fmt(subtotal)}</span>
              </div>
              {totalDisc > 0 && (
                <div style={{ display: 'flex', justifyContent: 'space-between', padding: '1.5mm 0', borderBottom: '1px solid #e2e8f0', color: '#ef4444' }}>
                  <span>Discount</span>
                  <span>- Rs. {fmt(totalDisc)}</span>
                </div>
              )}
              {parseFloat(sale.tax) > 0 && (
                <div style={{ display: 'flex', justifyContent: 'space-between', padding: '1.5mm 0', borderBottom: '1px solid #e2e8f0', color: '#64748b' }}>
                  <span>Tax</span>
                  <span>Rs. {fmt(sale.tax)}</span>
                </div>
              )}
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '2.5mm 3mm', backgroundColor: '#1e293b', color: 'white', fontWeight: 'bold', fontSize: '11pt', marginTop: '2mm', borderRadius: '2mm' }}>
                <span>TOTAL</span>
                <span>Rs. {fmt(sale.total)}</span>
              </div>
            </div>
          </div>

          {/* Payment method */}
          {payments.length > 0 && (
            <div style={{ marginBottom: '8mm', padding: '3mm 4mm', backgroundColor: '#f1f5f9', borderRadius: '2mm', fontSize: '9pt' }}>
              <span style={{ color: '#64748b', fontWeight: 'bold' }}>Payment: </span>
              {payments.map(p => (
                <span key={p.id} style={{ marginRight: '8mm', textTransform: 'capitalize', color: '#1e293b' }}>
                  {p.method} — Rs. {fmt(p.amount)}
                </span>
              ))}
            </div>
          )}

          {/* Note */}
          {sale.note && (
            <div style={{ marginBottom: '8mm', fontSize: '9pt', color: '#64748b' }}>
              <strong>Note:</strong> {sale.note}
            </div>
          )}

          {/* Footer */}
          <div style={{ borderTop: '1px solid #e2e8f0', paddingTop: '5mm', textAlign: 'center', fontSize: '8.5pt', color: '#94a3b8' }}>
            {rawSettings?.receipt_footer || 'Thank you for your business!'}
          </div>
        </div>
      </div>

      <style>{`
        @media print {
          @page { size: A4; margin: 0; }
          body > *:not(#root) { display: none; }
          .print\\:hidden { display: none !important; }
          html, body { background: white !important; overflow: visible !important; height: auto !important; }
          #root, #root > *, #root > * > * { overflow: visible !important; height: auto !important; max-height: none !important; }
        }
      `}</style>
    </>
  );
}

// resources/js/Pages/Sales/Show.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link } from '@inertiajs/vue3';
import { router } from '@inertiajs/vue3';
import { ref, computed, inject, onMounted } from 'vue';

const t     = inject('t');
const tBill = inject('tBill');

const props = defineProps({
    sale:     { type: Object, required: true },
    settings: { type: Object, default: () => ({}) },
});

const shopName    = computed(() => props.settings.shop_name    || 'LUMAC POS');
const shopAddress = computed(() => props.settings.shop_address || '');
const shopPhone   = computed(() => props.settings.shop_phone   || '');
const footer      = computed(() => props.settings.receipt_footer || '');
const currency    = computed(() => props.settings.currency     || 'Rs.');
const logoUrl     = computed(() => props.settings.logo_url     || null);

const paymentLabel = computed(() => {
    const map = { cash: tBill('lbl.cash'), card: tBill('lbl.card'), qr: 'QR', credit: tBill('lbl.credit') };
    return props.sale.payments?.[0]
        ? (map[props.sale.payments[0].method] || props.sale.payments[0].method)
        : '';
});

function fmtDate(d) {
    if (!d) return '';
    return new Date(d).toLocaleDateString('si-LK', { year: 'numeric', month: 'long', day: 'numeric' });
}

function fmtTime(d) {
    if (!d) return '';
    return new Date(d).toLocaleTimeString('en-LK', { hour: '2-digit', minute: '2-digit' });
}

function n(val) {
    return Number(val || 0).toFixed(2);
}

const profit = computed(() => {
    if (!props.sale.items?.length) return 0;
    return props.sale.items.reduce((sum, item) => {
        const revenue = Number(item.total || 0);
        const cost    = Number(item.cost_price || 0) * Number(item.qty || 0);
        return sum + (revenue - cost);
    }, 0);
});

async function printReceipt() {
    if (printing.value) return;
    printing.value = true;
    try {
        if (window.electronAPI?.isElectron) {
            const printer = localStorage.getItem('pos_printer') || '';
            const result  = await window.electronAPI.printReceipt(printer);
            if (!result?.success) {
                console.error('[print-receipt] failed:', result?.error);
                window.print();
            }
        } else {
            window.print();
        }
    } finally {
        setTimeout(() => { printing.value = false; }, 3000);
    }
}

const isElectron = !!window.electronAPI?.isElectron;
const printing   = ref(false);

onMounted(async () => {
    const params = new URLSearchParams(window.location.search);
    if (params.get('autoPrint') === '1') {
        await printReceipt();
        router.visit(route('sales.create'));
    }
});
</script>

<template>
    <Head :title="`${t('lbl.invoice_no')} ${sale.invoice_no}`" />

    <AuthenticatedLayout>
        <template #header>
            <div class="flex items-center gap-3">
                <Link :href="route('sales.index')" class="text-slate-400 hover:text-slate-600">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                    </svg>
                </Link>
                <h1 class="text-xl font-bold" style="color:#0F172A;">{{ sale.invoice_no }}</h1>
                <div class="ml-auto flex gap-2">
                    <Link
                        :href="route('sales.create')"
                        class="flex items-center gap-2 text-white px-4 py-2 rounded-lg text-sm font-semibold"
                        style="background-color:#16A34A;"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
                        </svg>
                        {{ t('btn.new_sale') }}
                    </Link>
                </div>
            </div>
        </template>

        <!-- Print button — fixed top-right -->
        <button
            type="button"
            @click="printReceipt"
            :disabled="printing"
            title="Print"
            class="no-print print-btn fixed z-50 flex items-center gap-2 text-white rounded-full shadow-lg overflow-hidden transition-all"
            :style="`top:72px; right:24px; height:44px; padding:0 16px 0 14px; background-color:${printing ? '#6B7280' : '#2563EB'}; cursor:${printing ? 'not-allowed' : 'pointer'};`"
        >
            <!-- Spinner while printing -->
            <svg v-if="printing" class="h-5 w-5 shrink-0 animate-spin" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"/>
            </svg>
            <!-- Printer icon normally -->
            <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            <span class="print-label text-sm font-semibold">{{ printing ? 'Printing…' : t('btn.print') }}</span>
        </button>

        <!-- Receipt centred on screen -->
        <div id="receipt-wrapper" class="flex flex-col items-center py-6 gap-4">
            <div id="receipt-card" class="bg-white rounded-xl shadow-sm p-8" style="border:1px solid #E2E8F0; width:340px;">

                <!-- Shop header -->
                <div class="text-center mb-4">
                    <img
                        v-if="logoUrl"
                        :src="logoUrl"
                        alt="Logo"
                        class="receipt-logo mx-auto mb-2 object-contain"
                        style="max-height:64px; max-width:180px;"
                    />
                    <p class="shop-title font-extrabold text-[16px]" style="color:#0F172A; letter-spacing:0.01em;">{{ shopName }}</p>
                    <p v-if="shopAddress" class="text-[12px] font-bold" style="color:#334155;">{{ shopAddress }}</p>
                    <p v-if="shopPhone" class="text-[12px] font-bold" style="color:#334155;">{{ shopPhone }}</p>
                </div>

                <div class="divider" style="border-top:1px dashed #CBD5E1; margin:10px 0;"></div>

                <!-- Invoice meta -->
                <div class="text-[12px] space-y-1 mb-1 font-bold" style="color:#1E293B;">
                    <div class="flex justify-between">
                        <span>{{ tBill('th.invoice') }}</span>
                        <span class="font-extrabold">{{ sale.invoice_no }}</span>
                    </div>
                    <div class="flex justify-between">
                        <span>{{ tBill('th.date') }}</span>
                        <span>{{ fmtDate(sale.created_at) }}</span>
                    </div>
                    <div class="flex justify-between">
                        <span>{{ tBill('th.time') }}</span>
                        <span>{{ fmtTime(sale.created_at) }}</span>
                    </div>
                    <div class="flex justify-between">
                        <span>{{ tBill('lbl.cashier') }}</span>
                        <span>{{ sale.user?.name }}</span>
                    </div>
                    <div v-if="sale.customer" class="flex justify-between">
                        <span>{{ tBill('lbl.customer') }}</span>
                        <span>{{ sale.customer.name }}</span>
                    </div>
                </div>

                <div class="items-section divider" style="border-top:1px dashed #CBD5E1; margin:10px 0;"></div>

                <!-- Items -->
                <table class="items-section" style="width:100%; border-collapse:collapse; font-size:12px; color:#0F172A; font-weight:800;">
                    <thead>
                        <tr style="border-bottom:2px solid #CBD5E1;">
                            <th style="text-align:left; width:16px; padding:4px 4px 4px 0; font-weight:800;">#</th>
                            <th style="text-align:left; padding:4px 8px 4px 0; font-weight:800;">{{ tBill('th.product') }}</th>
                            <th style="text-align:center; width:28px; padding:4px 0; font-weight:800;">{{ tBill('th.qty') }}</th>
                            <th style="text-align:right; width:52px; padding:4px 0; font-weight:800;">{{ tBill('th.price') }}</th>
                            <th style="text-align:right; width:48px; padding:4px 0; font-weight:800; color:#D97706;">{{ tBill('lbl.discount') }}</th>
                            <th style="text-align:right; width:56px; padding:4px 0; font-weight:800;">{{ tBill('lbl.total') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        <template v-for="(item, index) in sale.items" :key="item.id">
                            <!-- Line 1: item number + product names -->
                            <tr>
                                <td style="padding:4px 4px 0 0; font-weight:800; vertical-align:top;">{{ index + 1 }}</td>
                                <td colspan="5" style="padding:4px 8px 0 0; word-break:break-word; font-weight:800; color:#0F172A;">
                                    <span>{{ item.product_name?.split(' / ')[0] ?? item.product_name }}</span>
                                    <span v-if="item.product?.name_si" style="font-size:11px; font-weight:800; color:#334155;"> / {{ item.product.name_si }}</span>
                                </td>
                            </tr>
                            <!-- Line 2: qty / price / discount / total -->
                            <tr style="border-bottom:1px dashed #CBD5E1;">
                                <td style="padding:0 0 5px 0;"></td>
                                <td style="padding:0 0 5px 0;"></td>
                                <td style="text-align:center; padding:0 0 5px 0; font-weight:800;">{{ item.qty }}</td>
                                <td style="text-align:right; padding:0 0 5px 0; font-weight:800;">{{ n(item.unit_price) }}</td>
                                <td style="text-align:right; padding:0 0 5px 0; color:#D97706; font-weight:800;">{{ Number(item.discount) > 0 ? n(item.discount) : '-' }}</td>
                                <td style="text-align:right; padding:0 0 5px 0; font-weight:800; color:#0F172A;">{{ n(item.total) }}</td>
                            </tr>
                        </template>
                    </tbody>
                </table>

                <div class="items-section divider" style="border-top:1px dashed #CBD5E1; margin:10px 0;"></div>

                <!-- Totals -->
                <div class="space-y-1.5 text-[12px] font-bold" style="color:#0F172A;">
                    <div class="flex justify-between">
                        <span>{{ tBill('lbl.subtotal') }}</span>
                        <span>{{ n(sale.subtotal) }}</span>
                    </div>
                    <div v-if="Number(sale.discount) > 0" class="flex justify-between" style="color:#D97706;">
                        <span>{{ tBill('lbl.discount') }}</span>
                        <span>-{{ n(sale.discount) }}</span>
                    </div>
                    <div class="total-row flex justify-between text-[15px] pt-2" style="color:#0F172A; border-top:2px solid #0F172A; font-weight:800;">
                        <span>{{ tBill('lbl.total') }}</span>
                        <span style="color:#2563EB;">{{ currency }} {{ n(sale.total) }}</span>
                    </div>
                    <div class="flex justify-between" style="color:#16A34A;">
                        <span>{{ tBill('th.paid') }} ({{ paymentLabel }})</span>
                        <span>{{ n(sale.payments?.[0]?.amount) }}</span>
                    </div>
                    <div v-if="Number(sale.balance) < 0" class="flex justify-between">
                        <span>{{ tBill('lbl.change') }}</span>
                        <span>{{ n(Math.abs(sale.balance)) }}</span>
                    </div>
                </div>

                <div class="divider" style="border-top:1px dashed #CBD5E1; margin:10px 0;"></div>

                <!-- Footer -->
                <p class="text-center font-extrabold text-[13px]" style="color:#0F172A; white-space: pre-line;">{{ footer }}</p>

                <p class="text-center font-extrabold text-[11px] mt-3" style="color:#0F172A;">lunac.lk</p>
            </div>

        </div>
    </AuthenticatedLayout>
</template>

<style>
/* Print button pulse + label slide-in */
.print-btn {
    transition: box-shadow 0.2s, transform 0.2s;
    animation: print-pulse 2.5s ease-in-out infinite;
}
.print-btn:hover {
    transform: scale(1.06);
    box-shadow: 0 6px 20px rgba(37,99,235,0.45);
    animation: none;
}
.print-btn:active {
    transform: scale(0.96);
}
.print-label {
    display: inline-block;
    animation: label-slide 2.5s ease-in-out infinite;
}
@keyframes print-pulse {
    0%, 100% { box-shadow: 0 4px 14px rgba(37,99,235,0.35); }
    50%       { box-shadow: 0 4px 22px rgba(37,99,235,0.65); }
}
@keyframes label-slide {
    0%, 80%, 100% { opacity: 1; transform: translateX(0); }
    90%            { opacity: 0.6; transform: translateX(3px); }
}

@media print {
    @page {
        size: 80mm auto;
        margin: 0;
    }

    /* Hide entire page, then reveal only the receipt */
    html, body {
        margin: 0 !important;
        padding: 0 !important;
        width: 80mm !important;
    }

    body * {
        visibility: hidden !important;
    }

    #receipt-wrapper,
    #receipt-card,
    #receipt-card * {
        visibility: visible !important;
    }

    /* Pin wrapper to top-left, no gaps */
    #receipt-wrapper {
        position: fixed !important;
        top: 0 !important;
        left: 0 !important;
        width: 80mm !important;
        margin: 0 !important;
        padding: 0 !important;
        display: block !important;
    }

    /* Receipt card fills exactly 80mm */
    #receipt-card {
        position: static !important;
        width: 80mm !important;
        max-width: 80mm !important;
        padding: 4mm 5mm !important;
        margin: 0 !important;
        border: none !important;
        box-shadow: none !important;
        border-radius: 0 !important;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
    }

    #receipt-card * {
        font-weight: 800 !important;
    }

    #receipt-card .shop-title {
        font-size: 16px !important;
        font-weight: 800 !important;
    }

    #receipt-card .total-row,
    #receipt-card .total-row span {
        font-size: 15px !important;
        font-weight: 800 !important;
    }

    #receipt-card .divider {
        border-top: 1px dashed #555 !important;
        margin: 5px 0 !important;
    }

    #receipt-card .receipt-logo {
        max-height: 56px !important;
        max-width: 160px !important;
    }
}
</style>
