// pos-client/src/pages/Dashboard.jsx
import { useState, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { api } from '../app/baseApi';
import { useLocale } from '../contexts/LocaleContext';
import { selectRole } from '../features/auth/authSlice';
import ManagerDashboard from './ManagerDashboard';

const dashboardApi = api.injectEndpoints({
  endpoints: build => ({
    getDashboard: build.query({ query: () => '/dashboard', providesTags: ['Dashboard'] }),
  }),
  overrideExisting: false,
});

// ─── Helpers ─────────────────────────────────────────────────────────────────
function fmtRs(n) {
  return 'Rs. ' + parseFloat(n || 0).toLocaleString('en-LK', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}
function fmtShort(n) {
  const v = parseFloat(n || 0);
  if (v >= 1_000_000) return 'Rs. ' + (v / 1_000_000).toFixed(1) + 'M';
  if (v >= 1_000)     return 'Rs. ' + (v / 1_000).toFixed(1) + 'k';
  return 'Rs. ' + v.toFixed(2);
}
function dayLabel(dateStr) {
  const d  = new Date(dateStr);
  const today = new Date();
  const yest  = new Date(); yest.setDate(today.getDate() - 1);
  if (d.toDateString() === today.toDateString()) return 'Today';
  if (d.toDateString() === yest.toDateString())  return 'Yesterday';
  return d.toLocaleDateString('en-US', { weekday: 'short', day: 'numeric' });
}
function timeStr(s) {
  return new Date(s).toLocaleTimeString('en-LK', { hour: '2-digit', minute: '2-digit' });
}
function isoDate(d) { return d.toISOString().slice(0, 10); }

// ─── Stat Card ────────────────────────────────────────────────────────────────
function StatCard({ label, value, sub, icon, iconBg, valueColor = 'text-blue-600' }) {
  return (
    <div className="bg-white rounded-2xl p-5 border border-gray-300 shadow-sm flex items-start gap-4">
      <div className={`w-11 h-11 rounded-xl flex items-center justify-center shrink-0 ${iconBg}`}>
        {icon}
      </div>
      <div className="min-w-0">
        <p className="text-xs text-[#374151] font-semibold">{label}</p>
        <p className={`text-xl font-extrabold mt-0.5 leading-tight ${valueColor}`}>{value}</p>
        {sub && <p className="text-xs text-[#374151] mt-0.5">{sub}</p>}
      </div>
    </div>
  );
}

// ─── Hourly Chart ─────────────────────────────────────────────────────────────
const HOURS = [6, 8, 10, 12, 14, 16, 18, 20, 22];
const HOUR_LABELS = { 6:'6a', 8:'8a', 10:'10a', 12:'12p', 14:'2p', 16:'4p', 18:'6p', 20:'8p', 22:'10p' };

function HourlyChart({ hourlySales, dates }) {
  const [activeDay, setActiveDay] = useState(0);

  const byDate = useMemo(() => {
    const map = {};
    (hourlySales || []).forEach(r => {
      if (!map[r.date]) map[r.date] = {};
      map[r.date][parseInt(r.hour)] = parseFloat(r.total);
    });
    return map;
  }, [hourlySales]);

  const dateKey  = dates[activeDay];
  const dayData  = byDate[dateKey] || {};

  const points = Array.from({ length: 24 }, (_, h) => ({ h, v: dayData[h] ?? 0 }));
  const visible = points.filter(p => p.h >= 6 && p.h <= 22);
  const maxVal  = Math.max(...visible.map(p => p.v), 1);

  const W = 520, H = 100, PAD_X = 0, PAD_Y = 8;
  const xPos = h => PAD_X + ((h - 6) / 16) * W;
  const yPos = v => H - PAD_Y - ((v / maxVal) * (H - PAD_Y * 2));

  const pathPts = visible.map(p => `${xPos(p.h)},${yPos(p.v)}`).join(' ');
  const areaPath = `M${xPos(6)},${H - PAD_Y} ` +
    visible.map(p => `L${xPos(p.h)},${yPos(p.v)}`).join(' ') +
    ` L${xPos(22)},${H - PAD_Y} Z`;

  const totalDay   = Object.values(dayData).reduce((a, b) => a + b, 0);
  const billsToday = (hourlySales || []).filter(r => r.date === dateKey).reduce((a, r) => a + parseInt(r.bills), 0);

  return (
    <div className="bg-white rounded-2xl border border-gray-300 shadow-sm p-5 flex flex-col">
      <div className="flex items-start justify-between mb-3">
        <div>
          <p className="font-bold text-slate-800 text-sm">Sales — Last 3 Days</p>
          <p className="text-xs text-[#374151] mt-0.5">Hourly breakdown (6am – 10pm)</p>
        </div>
        <div className="flex gap-1">
          {dates.map((d, i) => (
            <button key={d} onClick={() => setActiveDay(i)}
              className={`px-2.5 py-1 text-xs font-semibold rounded-lg transition-colors ${
                i === activeDay
                  ? 'bg-blue-600 text-white'
                  : 'text-[#374151] hover:bg-slate-100'
              }`}>
              {dayLabel(d)}
            </button>
          ))}
        </div>
      </div>

      {/* Day totals row */}
      <div className="flex gap-6 mb-3">
        {dates.map((d, i) => {
          const dData  = byDate[d] || {};
          const dTotal = Object.values(dData).reduce((a, b) => a + b, 0);
          return (
            <div key={d} className="text-xs">
              <span className="text-[#374151]">{dayLabel(d)} </span>
              <span className={`font-bold ${i === activeDay ? 'text-blue-600' : 'text-[#374151]'}`}>
                {fmtShort(dTotal)}
              </span>
            </div>
          );
        })}
      </div>

      {/* SVG chart */}
      <div className="flex-1">
        <svg viewBox={`0 0 ${W} ${H}`} className="w-full" style={{ height: 100 }}>
          <defs>
            <linearGradient id="chartGrad" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%"   stopColor="#3b82f6" stopOpacity="0.25" />
              <stop offset="100%" stopColor="#3b82f6" stopOpacity="0" />
            </linearGradient>
          </defs>
          {[0.25, 0.5, 0.75, 1].map(f => (
            <line key={f}
              x1={0} y1={PAD_Y + (1 - f) * (H - PAD_Y * 2)}
              x2={W} y2={PAD_Y + (1 - f) * (H - PAD_Y * 2)}
              stroke="#f1f5f9" strokeWidth="1" />
          ))}
          <path d={areaPath} fill="url(#chartGrad)" />
          <polyline points={pathPts} fill="none" stroke="#3b82f6" strokeWidth="2" strokeLinejoin="round" />
          {visible.filter(p => p.v > 0).map(p => (
            <circle key={p.h} cx={xPos(p.h)} cy={yPos(p.v)} r="3" fill="#3b82f6" />
          ))}
        </svg>
        <div className="flex justify-between mt-1 px-0">
          {HOURS.map(h => (
            <span key={h} className="text-[10px] text-[#374151]">{HOUR_LABELS[h]}</span>
          ))}
        </div>
      </div>

      {/* Summary */}
      <div className="flex items-center gap-4 mt-2 pt-2 border-t border-slate-100">
        <div className="text-xs">
          <span className="text-[#374151]">Total: </span>
          <span className="font-bold text-blue-600">{fmtShort(totalDay)}</span>
        </div>
        <div className="text-xs">
          <span className="text-[#374151]">Bills: </span>
          <span className="font-bold text-slate-700">{billsToday}</span>
        </div>
      </div>
    </div>
  );
}

// ─── Quick Action Button ──────────────────────────────────────────────────────
function QuickBtn({ label, icon, color, onClick }) {
  return (
    <button onClick={onClick}
      className={`relative flex-1 flex flex-col items-center justify-center py-8 rounded-2xl text-white font-bold text-sm shadow-lg transition-transform hover:scale-[1.02] active:scale-[0.98] ${color}`}>
      <div className="w-12 h-12 rounded-full bg-white/20 flex items-center justify-center mb-2">
        {icon}
      </div>
      <span className="text-base font-bold">{label}</span>
    </button>
  );
}

// ─── Heatmap ─────────────────────────────────────────────────────────────────
const DOW_LABELS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

function Heatmap({ heatmap }) {
  const map = useMemo(() => {
    const m = {};
    (heatmap || []).forEach(r => { m[r.date] = parseFloat(r.total); });
    return m;
  }, [heatmap]);

  const maxVal = Math.max(...Object.values(map), 1);

  const today = new Date();
  const dow = today.getDay();
  const mondayOffset = dow === 0 ? 6 : dow - 1;
  const gridStart = new Date(today);
  gridStart.setDate(today.getDate() - mondayOffset - 69);

  const weeks = [];
  let cur = new Date(gridStart);
  const gridEnd = new Date(today);
  while (cur <= gridEnd) {
    const week = [];
    for (let d = 0; d < 7; d++) {
      week.push(isoDate(cur));
      cur.setDate(cur.getDate() + 1);
    }
    weeks.push(week);
  }

  function cellColor(val) {
    if (!val) return 'bg-[#E5E7EB]';
    const ratio = val / maxVal;
    if (ratio > 0.8) return 'bg-green-700';
    if (ratio > 0.6) return 'bg-green-600';
    if (ratio > 0.4) return 'bg-green-500';
    if (ratio > 0.2) return 'bg-green-400';
    return 'bg-green-200';
  }

  const weekLabels = weeks.map(w => new Date(w[0]).getDate());

  return (
    <div className="bg-white rounded-2xl border border-gray-300 shadow-sm p-5">
      <p className="font-bold text-slate-800 text-sm">Peak Days</p>
      <p className="text-xs text-[#374151] mt-0.5 mb-4">Sales heatmap — last 10 weeks</p>

      <div className="flex gap-2">
        {/* Row labels */}
        <div className="flex flex-col gap-1 pt-5">
          {DOW_LABELS.map(d => (
            <div key={d} className="h-4 flex items-center">
              <span className="text-[10px] text-[#374151] w-7">{d}</span>
            </div>
          ))}
        </div>

        {/* Grid */}
        <div className="flex-1 overflow-x-auto">
          <div className="flex gap-1 mb-1">
            {weekLabels.map((lbl, i) => (
              <div key={i} className="flex-1 text-center">
                <span className="text-[10px] text-[#374151]">{lbl}</span>
              </div>
            ))}
          </div>
          {DOW_LABELS.map((_, rowIdx) => (
            <div key={rowIdx} className="flex gap-1 mb-1">
              {weeks.map((week, wIdx) => {
                const dateKey = week[rowIdx];
                const val     = map[dateKey] ?? 0;
                return (
                  <div key={wIdx} title={dateKey + (val ? ` · Rs. ${val.toFixed(0)}` : '')}
                    className={`flex-1 h-4 rounded-sm cursor-default transition-opacity hover:opacity-80 ${cellColor(val)}`} />
                );
              })}
            </div>
          ))}
          {/* Legend */}
          <div className="flex items-center gap-1.5 mt-2">
            <span className="text-[10px] text-[#374151]">Less</span>
            {['bg-[#E5E7EB]','bg-green-200','bg-green-400','bg-green-500','bg-green-700'].map(c => (
              <div key={c} className={`w-3 h-3 rounded-sm ${c}`} />
            ))}
            <span className="text-[10px] text-[#374151]">More</span>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Recent Sales ─────────────────────────────────────────────────────────────
function RecentSales({ sales, onView }) {
  const { t } = useLocale();
  return (
    <div className="bg-white rounded-2xl border border-gray-300 shadow-sm p-5">
      <div className="flex items-center justify-between mb-4">
        <p className="font-bold text-slate-800 text-sm">{t('dash.recent_sales')}</p>
        <button onClick={onView} className="text-xs font-semibold text-blue-600 hover:text-blue-800">{t('dash.view_all')}</button>
      </div>
      {!sales?.length ? (
        <p className="text-sm text-[#374151] text-center py-6">{t('dash.no_sales')}</p>
      ) : (
        <div className="space-y-2">
          {sales.map(s => (
            <div key={s.id} className="flex items-center gap-3 py-2 border-b border-slate-100 last:border-0">
              <div className="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-white font-bold text-xs shrink-0">
                {s.user_name?.[0]?.toUpperCase()}
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-semibold text-blue-600 truncate">{s.invoice_no}</p>
                <p className="text-xs text-[#374151]">{s.user_name}</p>
              </div>
              <div className="text-right shrink-0">
                <p className="text-sm font-bold text-green-600">{fmtRs(s.total)}</p>
                <p className="text-xs text-[#374151]">{timeStr(s.created_at)}</p>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ─── Fast Moving ──────────────────────────────────────────────────────────────
function FastMoving({ items }) {
  const { t } = useLocale();
  const max = Math.max(...(items || []).map(i => parseInt(i.total_qty)), 1);
  return (
    <div className="bg-white rounded-2xl border border-gray-300 shadow-sm p-5">
      <div className="flex items-center justify-between mb-4">
        <p className="font-bold text-slate-800 text-sm">🔥 {t('pos.fast_moving')}</p>
        <span className="text-xs text-[#374151]">{t('lbl.this_month')}</span>
      </div>
      {!items?.length ? (
        <p className="text-sm text-[#374151] text-center py-6">{t('lbl.no_data')}</p>
      ) : (
        <div className="space-y-3">
          {items.map((item, i) => (
            <div key={i} className="flex items-center gap-3">
              <span className="text-xs font-bold text-[#374151] w-4 shrink-0">{i + 1}</span>
              <div className="w-8 h-8 rounded-lg bg-slate-100 flex items-center justify-center shrink-0 overflow-hidden">
                {item.image
                  ? <img src={item.image} alt="" className="w-full h-full object-cover" />
                  : <svg className="w-4 h-4 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"/></svg>
                }
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-semibold text-[#111827] truncate">{item.product_name}</p>
                <div className="flex items-center gap-2 mt-0.5">
                  <p className="text-xs text-[#374151]">{item.bill_count} bills</p>
                  <div className="flex-1 h-1.5 bg-slate-100 rounded-full overflow-hidden">
                    <div className="h-full bg-orange-400 rounded-full transition-all"
                      style={{ width: `${(parseInt(item.total_qty) / max) * 100}%` }} />
                  </div>
                  <span className="text-xs font-bold text-orange-500 shrink-0">{item.total_qty} sold</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ─── Main ─────────────────────────────────────────────────────────────────────
export default function Dashboard() {
  const role = useSelector(selectRole);
  if (role === 'manager') return <ManagerDashboard />;

  const { data, isLoading, refetch } = dashboardApi.useGetDashboardQuery();
  const navigate = useNavigate();
  const { t } = useLocale();

  if (isLoading) return (
    <div className="flex-1 flex items-center justify-center text-slate-400 text-sm">{t('lbl.loading')}</div>
  );

  const today = new Date();
  const dates = [2, 1, 0].map(n => {
    const d = new Date(today); d.setDate(today.getDate() - n); return isoDate(d);
  });

  const icons = {
    dollar: (
      <svg className="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>
      </svg>
    ),
    chart: (
      <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/>
      </svg>
    ),
    box: (
      <svg className="w-5 h-5 text-violet-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"/>
      </svg>
    ),
    alert: (
      <svg className="w-5 h-5 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/>
      </svg>
    ),
    pos: (
      <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 7H6a2 2 0 00-2 2v9a2 2 0 002 2h12a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1-4H9m0 0a2 2 0 000 4h6a2 2 0 000-4M9 3h6"/>
      </svg>
    ),
    product: (
      <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"/>
      </svg>
    ),
    purchase: (
      <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4"/>
      </svg>
    ),
    report: (
      <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
      </svg>
    ),
  };

  return (
    <div className="p-3 sm:p-6 space-y-4 sm:space-y-5 bg-[#F3F4F6] min-h-screen">

      {/* ── Row 1: Stats + Chart ─────────────────────────────────────────── */}
      <div className="grid grid-cols-1 lg:grid-cols-5 gap-5">
        <div className="lg:col-span-2 grid grid-cols-1 sm:grid-cols-2 gap-4 content-start">
          <StatCard
            label={t('dash.today_sales')} icon={icons.dollar} iconBg="bg-green-100"
            value={fmtRs(data?.todaySales)}
            sub={`${data?.todayBills || 0} bills today`}
            valueColor="text-green-600"
          />
          <StatCard
            label={t('dash.month_sales')} icon={icons.chart} iconBg="bg-blue-100"
            value={fmtRs(data?.monthSales)}
            sub={`${data?.monthBills || 0} bills this month`}
            valueColor="text-blue-600"
          />
          <StatCard
            label={t('dash.total_products')} icon={icons.box} iconBg="bg-violet-100"
            value={data?.totalProducts ?? 0}
            sub="active products"
            valueColor="text-violet-600"
          />
          <StatCard
            label={t('dash.low_stock')} icon={icons.alert} iconBg="bg-red-100"
            value={data?.lowStockCount ?? 0}
            sub="needs attention"
            valueColor="text-red-500"
          />
        </div>

        <div className="lg:col-span-3">
          <HourlyChart hourlySales={data?.hourlySales || []} dates={dates} />
        </div>
      </div>

      {/* ── Quick Actions ────────────────────────────────────────────────── */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4">
        <QuickBtn label={t('btn.new_sale')}     icon={icons.pos}      color="bg-[#1E40AF] hover:bg-blue-900"       onClick={() => navigate('/sales/create')} />
        <QuickBtn label={t('btn.new_product')}  icon={icons.product}  color="bg-purple-700 hover:bg-purple-800"    onClick={() => navigate('/products/create')} />
        <QuickBtn label={t('btn.new_purchase')} icon={icons.purchase} color="bg-[#15803D] hover:bg-green-900"      onClick={() => navigate('/purchases/create')} />
        <QuickBtn label={t('btn.report')}       icon={icons.report}   color="bg-orange-600 hover:bg-orange-700"    onClick={() => navigate('/reports')} />
      </div>

      {/* ── Bottom: Recent Sales + Fast Moving ───────────────────────────── */}
      <div className="grid grid-cols-1 lg:grid-cols-5 gap-5">
        <div className="lg:col-span-3">
          <RecentSales sales={data?.recentSales} onView={() => navigate('/sales')} />
        </div>
        <div className="lg:col-span-2">
          <FastMoving items={data?.fastMoving} />
        </div>
      </div>

    </div>
  );
}

// resources/js/Pages/Dashboard.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link } from '@inertiajs/vue3';
import { inject } from 'vue';

const t = inject('t');

const props = defineProps({
    todaySales: { type: Number, default: 0 },
    monthSales: { type: Number, default: 0 },
    totalProducts: { type: Number, default: 0 },
    lowStockCount: { type: Number, default: 0 },
    recentSales: { type: Array, default: () => [] },
});

function formatCurrency(value) {
    return 'Rs. ' + Number(value).toLocaleString('en-LK', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function formatTime(dateStr) {
    if (!dateStr) return '';
    const d = new Date(dateStr);
    return d.toLocaleTimeString('en-LK', { hour: '2-digit', minute: '2-digit' });
}

function formatDate(dateStr) {
    if (!dateStr) return '';
    const d = new Date(dateStr);
    return d.toLocaleDateString('si-LK');
}

const statCards = [
    {
        labelKey: 'dash.today_sales',
        valueKey: 'todaySales',
        isCurrency: true,
        bg: 'bg-green-500',
        lightBg: 'bg-green-50',
        textColor: 'text-green-700',
        icon: `<svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>`,
    },
    {
        labelKey: 'dash.month_sales',
        valueKey: 'monthSales',
        isCurrency: true,
        bg: 'bg-blue-500',
        lightBg: 'bg-blue-50',
        textColor: 'text-blue-700',
        icon: `<svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" /></svg>`,
    },
    {
        labelKey: 'dash.total_products',
        valueKey: 'totalProducts',
        isCurrency: false,
        bg: 'bg-purple-500',
        lightBg: 'bg-purple-50',
        textColor: 'text-purple-700',
        icon: `<svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" /></svg>`,
    },
    {
        labelKey: 'dash.low_stock',
        valueKey: 'lowStockCount',
        isCurrency: false,
        bg: 'bg-red-500',
        lightBg: 'bg-red-50',
        textColor: 'text-red-700',
        icon: `<svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>`,
    },
];
</script>

<template>
    <Head :title="t('page.dashboard')" />

    <AuthenticatedLayout>
        <template #header>
            <h1 class="text-xl font-bold text-gray-800">{{ t('page.dashboard') }}</h1>
        </template>

        <!-- Stat Cards -->
        <div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
            <div
                v-for="card in statCards"
                :key="card.valueKey"
                class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden"
            >
                <div class="p-5">
                    <div class="flex items-center gap-4 mb-3">
                        <div :class="[card.bg, 'w-14 h-14 rounded-xl flex-shrink-0 flex items-center justify-center']">
                            <span v-html="card.icon"></span>
                        </div>
                        <p class="stat-card-value font-bold text-gray-900 text-xl truncate">
                            <template v-if="card.isCurrency">
                                {{ formatCurrency(props[card.valueKey]) }}
                            </template>
                            <template v-else>
                                {{ props[card.valueKey] }}
                            </template>
                        </p>
                    </div>
                    <p class="stat-card-label font-semibold text-gray-600 text-base">{{ t(card.labelKey) }}</p>
                </div>
            </div>
        </div>

        <!-- Quick Actions -->
        <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
            <!-- New Sale -->
            <Link :href="route('sales.create')" class="quick-action-card group" style="--from:#2563EB;--to:#1d4ed8;">
                <div class="quick-action-glow" style="background:radial-gradient(circle at 70% 30%, rgba(255,255,255,0.18) 0%, transparent 70%);"></div>
                <div class="quick-action-icon-wrap">
                    <svg xmlns="http://www.w3.org/2000/svg" class="quick-action-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-1.5 6h13M10 19a1 1 0 100 2 1 1 0 000-2zm7 0a1 1 0 100 2 1 1 0 000-2z" />
                    </svg>
                </div>
                <span class="quick-action-plus">+</span>
                <span class="quick-action-label">{{ t('btn.new_sale') }}</span>
                <div class="quick-action-arrow">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                    </svg>
                </div>
            </Link>

            <!-- New Product -->
            <Link :href="route('products.create')" class="quick-action-card group" style="--from:#7C3AED;--to:#6D28D9;">
                <div class="quick-action-glow" style="background:radial-gradient(circle at 70% 30%, rgba(255,255,255,0.18) 0%, transparent 70%);"></div>
                <div class="quick-action-icon-wrap">
                    <svg xmlns="http://www.w3.org/2000/svg" class="quick-action-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
                    </svg>
                </div>
                <span class="quick-action-plus">+</span>
                <span class="quick-action-label">{{ t('btn.new_product') }}</span>
                <div class="quick-action-arrow">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                    </svg>
                </div>
            </Link>

            <!-- New Purchase -->
            <Link :href="route('purchases.create')" class="quick-action-card group" style="--from:#059669;--to:#047857;">
                <div class="quick-action-glow" style="background:radial-gradient(circle at 70% 30%, rgba(255,255,255,0.18) 0%, transparent 70%);"></div>
                <div class="quick-action-icon-wrap">
                    <svg xmlns="http://www.w3.org/2000/svg" class="quick-action-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                    </svg>
                </div>
                <span class="quick-action-plus">+</span>
                <span class="quick-action-label">{{ t('btn.new_purchase') }}</span>
                <div class="quick-action-arrow">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                    </svg>
                </div>
            </Link>

            <!-- Reports -->
            <Link :href="route('reports.index')" class="quick-action-card group" style="--from:#D97706;--to:#B45309;">
                <div class="quick-action-glow" style="background:radial-gradient(circle at 70% 30%, rgba(255,255,255,0.18) 0%, transparent 70%);"></div>
                <div class="quick-action-icon-wrap">
                    <svg xmlns="http://www.w3.org/2000/svg" class="quick-action-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                </div>
                <span class="quick-action-label">{{ t('btn.report') }}</span>
                <div class="quick-action-arrow">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                    </svg>
                </div>
            </Link>
        </div>

        <!-- Recent Sales Table -->
        <div class="bg-white rounded-xl shadow-sm border border-gray-100">
            <div class="flex items-center justify-between px-4 py-3 border-b border-gray-100">
                <h2 class="font-semibold text-gray-800">{{ t('dash.recent_sales') }}</h2>
                <Link :href="route('sales.index')" class="text-sm hover:underline" style="color:#2563EB;">{{ t('dash.view_all') }}</Link>
            </div>

            <!-- Mobile card view -->
            <div class="md:hidden divide-y divide-gray-100">
                <div v-if="recentSales.length === 0" class="p-6 text-center text-gray-400">
                    <p>{{ t('dash.no_sales') }}</p>
                </div>
                <div
                    v-for="sale in recentSales"
                    :key="sale.id"
                    class="p-4"
                >
                    <div class="flex justify-between items-start">
                        <div>
                            <Link :href="route('sales.show', sale.id)" class="font-medium hover:underline" style="color:#2563EB;">{{ sale.invoice_no }}</Link>
                            <p class="text-sm text-gray-500">{{ sale.user?.name }}</p>
                        </div>
                        <div class="text-right">
                            <p class="font-semibold text-green-600">{{ formatCurrency(sale.total) }}</p>
                            <p class="text-xs text-gray-400">{{ formatTime(sale.created_at) }}</p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Desktop table view -->
            <div class="hidden md:block overflow-x-auto">
                <table class="w-full">
                    <thead>
                        <tr class="text-left text-xs font-semibold text-gray-500 uppercase tracking-wider bg-gray-50">
                            <th class="px-4 py-3">{{ t('th.invoice') }}</th>
                            <th class="px-4 py-3">{{ t('th.cashier') }}</th>
                            <th class="px-4 py-3">{{ t('th.total') }}</th>
                            <th class="px-4 py-3">{{ t('th.time') }}</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-100">
                        <tr v-if="recentSales.length === 0">
                            <td colspan="4" class="px-4 py-8 text-center text-gray-400">{{ t('dash.no_sales') }}</td>
                        </tr>
                        <tr
                            v-for="sale in recentSales"
                            :key="sale.id"
                            class="hover:bg-gray-50 transition-colors"
                        >
                            <td class="px-4 py-3">
                                <Link :href="route('sales.show', sale.id)" class="font-medium hover:underline" style="color:#2563EB;">{{ sale.invoice_no }}</Link>
                            </td>
                            <td class="px-4 py-3 text-gray-600">{{ sale.user?.name }}</td>
                            <td class="px-4 py-3 font-semibold text-green-600">{{ formatCurrency(sale.total) }}</td>
                            <td class="px-4 py-3 text-gray-400 text-sm">{{ formatTime(sale.created_at) }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </AuthenticatedLayout>
</template>

<style scoped>
.quick-action-card {
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 6px;
    padding: 1.25rem 1rem;
    min-height: 110px;
    border-radius: 1rem;
    background: linear-gradient(135deg, var(--from), var(--to));
    color: #fff;
    text-decoration: none;
    overflow: hidden;
    box-shadow: 0 4px 15px rgba(0,0,0,0.15);
    transition: transform 0.2s ease, box-shadow 0.2s ease;
}
.quick-action-card:hover {
    transform: translateY(-3px) scale(1.02);
    box-shadow: 0 8px 25px rgba(0,0,0,0.22);
}
.quick-action-card:active {
    transform: translateY(0) scale(0.98);
}
.quick-action-glow {
    position: absolute;
    inset: 0;
    pointer-events: none;
}
.quick-action-icon-wrap {
    width: 48px;
    height: 48px;
    border-radius: 50%;
    background: rgba(255,255,255,0.2);
    display: flex;
    align-items: center;
    justify-content: center;
    backdrop-filter: blur(4px);
    border: 1px solid rgba(255,255,255,0.3);
    transition: background 0.2s;
}
.quick-action-card:hover .quick-action-icon-wrap {
    background: rgba(255,255,255,0.3);
}
.quick-action-icon {
    width: 24px;
    height: 24px;
    color: #fff;
}
.quick-action-plus {
    position: absolute;
    top: 10px;
    right: 14px;
    font-size: 1.4rem;
    font-weight: 300;
    opacity: 0.7;
    line-height: 1;
}
.quick-action-label {
    font-size: 0.8rem;
    font-weight: 600;
    letter-spacing: 0.01em;
    text-align: center;
    line-height: 1.3;
}
.quick-action-arrow {
    position: absolute;
    bottom: 10px;
    right: 12px;
    opacity: 0;
    transform: translateX(-4px);
    transition: opacity 0.2s, transform 0.2s;
}
.quick-action-card:hover .quick-action-arrow {
    opacity: 0.7;
    transform: translateX(0);
}
</style>
